import { LevelConfig } from './LevelTypes';

/**
 * 第7章：记忆圣殿 (Chapter 7: Memory Temple)
 * 主题：神圣的记忆殿堂，光芒与圣洁，古老神殿
 * 风格：金色圣光，庄严石柱，天使回响
 */

export const Chapter7Stages: LevelConfig[] = [
  // ========== 教学/入门区域 (第1-10关) 难度1-2 ==========
  {
    id: 'ch7_stage_001',
    name: '圣殿之门',
    chapter: 7,
    stageNumber: 1,
    description: '记忆圣殿的宏伟入口在前方展开，金色圣光照耀着你的道路。',
    background: 'temple_gate',
    difficulty: 1,
    enemyIds: ['holy_wisp_001'],
    enemyLevel: 1,
    isBossLevel: false,
    rewards: { exp: 80, gold: 160, memoryShards: 11 }
  },
  {
    id: 'ch7_stage_002',
    name: '圣光走廊',
    chapter: 7,
    stageNumber: 2,
    description: '走廊两侧排列着古老的圣像，柔和的光芒指引前行。',
    background: 'light_corridor',
    difficulty: 1,
    enemyIds: ['holy_wisp_001', 'holy_wisp_002'],
    enemyLevel: 1,
    isBossLevel: false,
    rewards: { exp: 85, gold: 170, memoryShards: 11 }
  },
  {
    id: 'ch7_stage_003',
    name: '祈祷大厅',
    chapter: 7,
    stageNumber: 3,
    description: '巨大的祈祷厅回荡着神圣的吟唱，空气中弥漫着庄严。',
    background: 'prayer_hall',
    difficulty: 1,
    enemyIds: ['prayer_spirit_001'],
    enemyLevel: 1,
    isBossLevel: false,
    rewards: { exp: 90, gold: 180, memoryShards: 12 }
  },
  {
    id: 'ch7_stage_004',
    name: '星光穹顶',
    chapter: 7,
    stageNumber: 4,
    description: '穹顶上绘制的星辰图似乎在缓缓转动，记录着远古的记忆。',
    background: 'star_dome',
    difficulty: 1,
    enemyIds: ['star_pilgrim_001', 'holy_wisp_001'],
    enemyLevel: 1,
    isBossLevel: false,
    rewards: { exp: 95, gold: 190, memoryShards: 12 }
  },
  {
    id: 'ch7_stage_005',
    name: '圣水池畔',
    chapter: 7,
    stageNumber: 5,
    description: '清澈的圣水散发着治愈的光芒，但守护者不让轻易靠近。',
    background: 'holy_water_pool',
    difficulty: 2,
    enemyIds: ['water_guardian_001'],
    enemyLevel: 2,
    isBossLevel: false,
    rewards: { exp: 105, gold: 210, memoryShards: 13 }
  },
  {
    id: 'ch7_stage_006',
    name: '回音圣殿',
    chapter: 7,
    stageNumber: 6,
    description: '古老的祈祷声在这里回荡了千年，形成了一种神秘的力量。',
    background: 'echoing_sanctuary',
    difficulty: 2,
    enemyIds: ['echo_chant_001'],
    enemyLevel: 2,
    isBossLevel: false,
    rewards: { exp: 110, gold: 220, memoryShards: 13 }
  },
  {
    id: 'ch7_stage_007',
    name: '光之阶梯',
    chapter: 7,
    stageNumber: 7,
    description: '通往高处的阶梯由纯粹的光芒构成，每一步都充满神圣。',
    background: 'light_staircase',
    difficulty: 2,
    enemyIds: ['stair_keeper_001', 'holy_wisp_002'],
    enemyLevel: 2,
    isBossLevel: false,
    rewards: { exp: 115, gold: 230, memoryShards: 14 }
  },
  {
    id: 'ch7_stage_008',
    name: '神圣花园',
    chapter: 7,
    stageNumber: 8,
    description: '花园中盛开着永不凋谢的神圣之花，散发着净化之力。',
    background: 'sacred_garden',
    difficulty: 2,
    enemyIds: ['garden_seraph_001'],
    enemyLevel: 2,
    isBossLevel: false,
    rewards: { exp: 120, gold: 240, memoryShards: 14 }
  },
  {
    id: 'ch7_stage_009',
    name: '守护雕像',
    chapter: 7,
    stageNumber: 9,
    description: '古老的守护雕像开始苏醒，它们要考验每一个进入者。',
    background: 'guardian_statues',
    difficulty: 2,
    enemyIds: ['living_statue_001', 'prayer_spirit_001'],
    enemyLevel: 2,
    isBossLevel: false,
    rewards: { exp: 125, gold: 250, memoryShards: 15 }
  },
  {
    id: 'ch7_stage_010',
    name: '圣殿卫士',
    chapter: 7,
    stageNumber: 10,
    description: '由圣光凝聚而成的守卫挡在前方，只有通过考验才能继续前进。',
    background: 'temple_guardian_gate',
    difficulty: 2,
    enemyIds: ['holy_guardian_001'],
    enemyLevel: 3,
    isBossLevel: true,
    rewards: { exp: 180, gold: 450, memoryShards: 28 }
  },
  // ========== 初级区域 (第11-20关) 难度2-3 ==========
  {
    id: 'ch7_stage_011',
    name: '深入圣殿',
    chapter: 7,
    stageNumber: 11,
    description: '开始向圣殿深处探索，神圣的力量愈发浓郁。',
    background: 'deep_temple',
    difficulty: 2,
    enemyIds: ['deep_temple_wanderer_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 160, gold: 320, memoryShards: 16 }
  },
  {
    id: 'ch7_stage_012',
    name: '圣杯之间',
    chapter: 7,
    stageNumber: 12,
    description: '无数圣杯陈列于此，每一只都盛装着不同的神圣记忆。',
    background: 'chalice_chamber',
    difficulty: 2,
    enemyIds: ['chalice_keeper_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 165, gold: 330, memoryShards: 16 }
  },
  {
    id: 'ch7_stage_013',
    name: '天使画廊',
    chapter: 7,
    stageNumber: 13,
    description: '画廊中的天使画像栩栩如生，仿佛随时会从画中走出。',
    background: 'angel_gallery',
    difficulty: 2,
    enemyIds: ['painted_angel_001', 'holy_wisp_003'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 170, gold: 340, memoryShards: 17 }
  },
  {
    id: 'ch7_stage_014',
    name: '光明祭坛',
    chapter: 7,
    stageNumber: 14,
    description: '祭坛上的圣火燃烧了千年，照亮着通往真理的道路。',
    background: 'light_altar',
    difficulty: 3,
    enemyIds: ['altar_flame_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 180, gold: 360, memoryShards: 18 }
  },
  {
    id: 'ch7_stage_015',
    name: '神圣钟楼',
    chapter: 7,
    stageNumber: 15,
    description: '古老的钟楼敲响着时间的钟声，每一声都是记忆的回响。',
    background: 'sacred_bell_tower',
    difficulty: 3,
    enemyIds: ['bell_spirit_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 185, gold: 370, memoryShards: 18 }
  },
  {
    id: 'ch7_stage_016',
    name: '启示之间',
    chapter: 7,
    stageNumber: 16,
    description: '在这里，过去的先知们曾接受神圣的启示。',
    background: 'revelation_chamber',
    difficulty: 3,
    enemyIds: ['revelation_ghost_001', 'seer_spirit_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 190, gold: 380, memoryShards: 19 }
  },
  {
    id: 'ch7_stage_017',
    name: '圣咏之泉',
    chapter: 7,
    stageNumber: 17,
    description: '泉水流淌出优美的圣咏，但也隐藏着守护的力量。',
    background: 'chanting_spring',
    difficulty: 3,
    enemyIds: ['spring_seraph_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 195, gold: 390, memoryShards: 19 }
  },
  {
    id: 'ch7_stage_018',
    name: '镜像圣殿',
    chapter: 7,
    stageNumber: 18,
    description: '镜子反射着无数神圣的光芒，创造出迷离的空间。',
    background: 'mirrored_sanctuary',
    difficulty: 3,
    enemyIds: ['mirror_seraph_001', 'light_reflection_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 200, gold: 400, memoryShards: 20 }
  },
  {
    id: 'ch7_stage_019',
    name: '天使之路',
    chapter: 7,
    stageNumber: 19,
    description: '传说中的天使曾走过这条道路，留下了神圣的痕迹。',
    background: 'angel_path',
    difficulty: 3,
    enemyIds: ['fallen_angel_trace_001', 'holy_trail_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 205, gold: 410, memoryShards: 20 }
  },
  {
    id: 'ch7_stage_020',
    name: '初级天使',
    chapter: 7,
    stageNumber: 20,
    description: '一位守护圣殿的天使降临，她的力量令人敬畏。',
    background: 'junior_angel_arena',
    difficulty: 3,
    enemyIds: ['guardian_angel_001'],
    enemyLevel: 4,
    isBossLevel: true,
    rewards: { exp: 300, gold: 700, memoryShards: 54 }
  },
  // ========== 中级区域 (第21-30关) 难度3-4 ==========
  {
    id: 'ch7_stage_021',
    name: '圣殿之心',
    chapter: 7,
    stageNumber: 21,
    description: '到达圣殿的核心地带，神圣能量浓郁到几乎化为实质。',
    background: 'temple_heart',
    difficulty: 3,
    enemyIds: ['heart_holy_sentinel_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 225, gold: 450, memoryShards: 23 }
  },
  {
    id: 'ch7_stage_022',
    name: '记忆圣坛',
    chapter: 7,
    stageNumber: 22,
    description: '圣坛上供奉着最珍贵的记忆，被神圣的力量守护着。',
    background: 'memory_shrine',
    difficulty: 3,
    enemyIds: ['shrine_memory_keeper_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 230, gold: 460, memoryShards: 23 }
  },
  {
    id: 'ch7_stage_023',
    name: '大天使殿堂',
    chapter: 7,
    stageNumber: 23,
    description: '宏伟的殿堂中，大天使们的雕像俯瞰着一切。',
    background: 'archangel_hall',
    difficulty: 4,
    enemyIds: ['archangel_statue_001', 'seraphim_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 240, gold: 480, memoryShards: 25 }
  },
  {
    id: 'ch7_stage_024',
    name: '圣光风暴',
    chapter: 7,
    stageNumber: 24,
    description: '纯粹圣光形成的风暴在殿堂中肆虐，净化一切不洁。',
    background: 'holy_storm_chamber',
    difficulty: 4,
    enemyIds: ['storm_seraph_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 245, gold: 490, memoryShards: 25 }
  },
  {
    id: 'ch7_stage_025',
    name: '神圣编织者',
    chapter: 7,
    stageNumber: 25,
    description: '一位神秘的存在正在编织神圣的记忆，创造光明的未来。',
    background: 'holy_weaver_chamber',
    difficulty: 4,
    enemyIds: ['holy_weaver_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 250, gold: 500, memoryShards: 26 }
  },
  {
    id: 'ch7_stage_026',
    name: '古老圣殿',
    chapter: 7,
    stageNumber: 26,
    description: '比圣殿本身更古老的遗迹，记录着最初的信仰。',
    background: 'ancient_temple_ruins',
    difficulty: 4,
    enemyIds: ['ancient_holy_guardian_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 255, gold: 510, memoryShards: 26 }
  },
  {
    id: 'ch7_stage_027',
    name: '神圣试炼',
    chapter: 7,
    stageNumber: 27,
    description: '圣殿设下的试炼场，只有最纯净的灵魂才能通过。',
    background: 'holy_trial_grounds',
    difficulty: 4,
    enemyIds: ['trial_seraph_001', 'purification_warden_001', 'light_judge_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 260, gold: 520, memoryShards: 27 }
  },
  {
    id: 'ch7_stage_028',
    name: '圣殿圣女',
    chapter: 7,
    stageNumber: 28,
    description: '圣殿的圣女显现，她的祝福也是强大的力量。',
    background: 'saintess_chamber',
    difficulty: 4,
    enemyIds: ['temple_saintess_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 265, gold: 530, memoryShards: 27 }
  },
  {
    id: 'ch7_stage_029',
    name: '圣殿觉醒',
    chapter: 7,
    stageNumber: 29,
    description: '圣殿本身开始觉醒，它的意志在观察着你的一举一动。',
    background: 'awakened_temple',
    difficulty: 4,
    enemyIds: ['temple_eye_001', 'holy_warden_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 270, gold: 540, memoryShards: 28 }
  },
  {
    id: 'ch7_stage_030',
    name: '中级天使长',
    chapter: 7,
    stageNumber: 30,
    description: '一位强大的天使长降临，他的光芒照耀整个殿堂。',
    background: 'mid_archangel_arena',
    difficulty: 4,
    enemyIds: ['powerful_archangel_001'],
    enemyLevel: 5,
    isBossLevel: true,
    rewards: { exp: 420, gold: 1020, memoryShards: 80 }
  },
  // ========== 高级区域 (第31-40关) 难度4-5 ==========
  {
    id: 'ch7_stage_031',
    name: '圣殿深渊',
    chapter: 7,
    stageNumber: 31,
    description: '深入圣殿最神圣的区域，这里居住着最强大的神圣生物。',
    background: 'temple_abyss',
    difficulty: 4,
    enemyIds: ['abyss_seraph_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 285, gold: 570, memoryShards: 32 }
  },
  {
    id: 'ch7_stage_032',
    name: '光暗交织',
    chapter: 7,
    stageNumber: 32,
    description: '光明与黑暗在这里交汇，形成独特的神圣空间。',
    background: 'light_dark_intersection',
    difficulty: 4,
    enemyIds: ['twilight_seraph_001', 'dawn_guardian_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 290, gold: 580, memoryShards: 32 }
  },
  {
    id: 'ch7_stage_033',
    name: '神圣愤怒',
    chapter: 7,
    stageNumber: 33,
    description: '圣殿对入侵者感到愤怒，神圣之力开始狂暴地涌动。',
    background: 'angry_holy_chamber',
    difficulty: 5,
    enemyIds: ['wrathful_seraph_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 305, gold: 610, memoryShards: 34 }
  },
  {
    id: 'ch7_stage_034',
    name: '神圣囚牢',
    chapter: 7,
    stageNumber: 34,
    description: '被囚禁的神圣灵魂在此，它们渴望解脱却成为新的威胁。',
    background: 'holy_prison',
    difficulty: 5,
    enemyIds: ['imprisoned_seraph_001', 'holy_jailer_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 310, gold: 620, memoryShards: 34 }
  },
  {
    id: 'ch7_stage_035',
    name: '无限圣光',
    chapter: 7,
    stageNumber: 35,
    description: '光芒似乎没有尽头，无论走到哪里都被神圣包围。',
    background: 'infinite_light',
    difficulty: 5,
    enemyIds: ['light_loop_seraph_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 315, gold: 630, memoryShards: 35 }
  },
  {
    id: 'ch7_stage_036',
    name: '远古圣殿',
    chapter: 7,
    stageNumber: 36,
    description: '这里封印着最古老的神圣之力，连时间都无法侵蚀。',
    background: 'primordial_sanctuary',
    difficulty: 5,
    enemyIds: ['ancient_seraph_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 320, gold: 640, memoryShards: 35 }
  },
  {
    id: 'ch7_stage_037',
    name: '圣殿意志',
    chapter: 7,
    stageNumber: 37,
    description: '圣殿凝聚出了自己的意志，它要考验每一个深入者。',
    background: 'will_of_temple',
    difficulty: 5,
    enemyIds: ['temple_will_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 325, gold: 650, memoryShards: 36 }
  },
  {
    id: 'ch7_stage_038',
    name: '圣光漩涡',
    chapter: 7,
    stageNumber: 38,
    description: '一个巨大的圣光漩涡正在形成，吞噬着周围的一切黑暗。',
    background: 'holy_vortex',
    difficulty: 5,
    enemyIds: ['vortex_seraph_001', 'purified_being_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 330, gold: 660, memoryShards: 36 }
  },
  {
    id: 'ch7_stage_039',
    name: '最后的朝圣',
    chapter: 7,
    stageNumber: 39,
    description: '进入精英区域前的最后朝圣，你将面对圣殿最深的秘密。',
    background: 'final_pilgrimage_chamber',
    difficulty: 5,
    enemyIds: ['pilgrimage_sentinel_001', 'holy_guardian_002'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 335, gold: 670, memoryShards: 37 }
  },
  {
    id: 'ch7_stage_040',
    name: '高级炽天使',
    chapter: 7,
    stageNumber: 40,
    description: '炽天使之王降临圣殿，他的火焰净化一切邪恶。',
    background: 'high_seraph_arena',
    difficulty: 5,
    enemyIds: ['seraphim_king_001'],
    enemyLevel: 6,
    isBossLevel: true,
    rewards: { exp: 520, gold: 1280, memoryShards: 114 }
  },
  // ========== 精英区域 (第41-49关) 难度5 ==========
  {
    id: 'ch7_stage_041',
    name: '圣殿核心',
    chapter: 7,
    stageNumber: 41,
    description: '精英区域的起始，圣殿最深处，神圣达到极致。',
    background: 'temple_core',
    difficulty: 5,
    enemyIds: ['core_holy_defender_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 375, gold: 750, memoryShards: 39 }
  },
  {
    id: 'ch7_stage_042',
    name: '神圣王座',
    chapter: 7,
    stageNumber: 42,
    description: '一座由纯粹光芒构成的王座，散发着创造般的力量。',
    background: 'divine_throne',
    difficulty: 5,
    enemyIds: ['throne_divine_keeper_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 380, gold: 760, memoryShards: 39 }
  },
  {
    id: 'ch7_stage_043',
    name: '无尽光芒',
    chapter: 7,
    stageNumber: 43,
    description: '光芒似乎没有边界，延伸到无限的圣洁之中。',
    background: 'endless_light_chamber',
    difficulty: 5,
    enemyIds: ['infinite_light_being_001', 'light_lord_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 385, gold: 770, memoryShards: 40 }
  },
  {
    id: 'ch7_stage_044',
    name: '圣光之源',
    chapter: 7,
    stageNumber: 44,
    description: '所有圣光的源头，一个古老而神圣的存在守护着这里。',
    background: 'source_of_light',
    difficulty: 5,
    enemyIds: ['light_source_guardian_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 390, gold: 780, memoryShards: 40 }
  },
  {
    id: 'ch7_stage_045',
    name: '圣殿大祭司',
    chapter: 7,
    stageNumber: 45,
    description: '圣殿的最高祭司，掌控着神圣与记忆的终极秘密。',
    background: 'high_priest_chamber',
    difficulty: 5,
    enemyIds: ['temple_high_priest_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 395, gold: 790, memoryShards: 41 }
  },
  {
    id: 'ch7_stage_046',
    name: '禁忌神圣',
    chapter: 7,
    stageNumber: 46,
    description: '被封印的禁忌神圣之力，任何进入者都将面对最艰难的考验。',
    background: 'forbidden_divine',
    difficulty: 5,
    enemyIds: ['forbidden_holy_keeper_001', 'cursed_seraph_001'],
    enemyLevel: 7,
    isBossLevel: false,
    rewards: { exp: 400, gold: 800, memoryShards: 41 }
  },
  {
    id: 'ch7_stage_047',
    name: '圣殿的真相',
    chapter: 7,
    stageNumber: 47,
    description: '开始接近记忆圣殿的真相，守卫变得更加神圣而强大。',
    background: 'truth_of_temple_chamber',
    difficulty: 5,
    enemyIds: ['temple_truth_guardian_001'],
    enemyLevel: 7,
    isBossLevel: false,
    rewards: { exp: 405, gold: 810, memoryShards: 42 }
  },
  {
    id: 'ch7_stage_048',
    name: '神圣巅峰',
    chapter: 7,
    stageNumber: 48,
    description: '普通神圣的巅峰，在这里你将面对最强大的神圣生物。',
    background: 'divine_peak',
    difficulty: 5,
    enemyIds: ['peak_divine_being_001'],
    enemyLevel: 7,
    isBossLevel: false,
    rewards: { exp: 410, gold: 820, memoryShards: 42 }
  },
  {
    id: 'ch7_stage_049',
    name: '终极圣殿守卫',
    chapter: 7,
    stageNumber: 49,
    description: '精英区域的最终守卫，击败它才能面对章节Boss。',
    background: 'ultimate_temple_gate',
    difficulty: 5,
    enemyIds: ['ultimate_holy_sentinel_001', 'ultimate_divine_defender_001'],
    enemyLevel: 7,
    isBossLevel: false,
    rewards: { exp: 415, gold: 830, memoryShards: 43 }
  },
  // ========== 章节Boss (第50关) 难度6 ==========
  {
    id: 'ch7_stage_050',
    name: '圣殿之主',
    chapter: 7,
    stageNumber: 50,
    description: '记忆圣殿的真正主宰，她是神圣与记忆的化身，掌控着所有被祝福的记忆与存在。她能召唤圣光审判，净化一切黑暗。只有战胜她，才能领悟记忆的真谛。',
    background: 'temple_master_throne',
    difficulty: 6,
    enemyIds: ['temple_overlord_001'],
    enemyLevel: 8,
    isBossLevel: true,
    rewards: { exp: 900, gold: 2400, memoryShards: 220 }
  }
];

export default Chapter7Stages;
