import { LevelConfig } from './LevelTypes';

/**
 * 第4章：愤怒火山 (Chapter 4: Raging Volcano)
 * 主题：愤怒的火山，岩浆与火焰，毁灭与重生
 * 风格：炽热岩浆，火山灰弥漫，炙热熔岩
 */

export const Chapter4Stages: LevelConfig[] = [
  // ========== 教学/入门区域 (第1-10关) 难度1-2 ==========
  {
    id: 'ch4_stage_001',
    name: '火山初临',
    chapter: 4,
    stageNumber: 1,
    description: '你来到愤怒火山的山脚，空气中弥漫着硫磺的气息。',
    background: 'volcano_foot',
    difficulty: 1,
    enemyIds: ['ash_sprite_001'],
    enemyLevel: 1,
    isBossLevel: false,
    rewards: { exp: 65, gold: 130, memoryShards: 8 }
  },
  {
    id: 'ch4_stage_002',
    name: '硫磺小径',
    chapter: 4,
    stageNumber: 2,
    description: '硫磺小径蜿蜒向上，地面散发着阵阵热气。',
    background: 'sulfur_path',
    difficulty: 1,
    enemyIds: ['ash_sprite_001', 'ash_sprite_002'],
    enemyLevel: 1,
    isBossLevel: false,
    rewards: { exp: 70, gold: 140, memoryShards: 8 }
  },
  {
    id: 'ch4_stage_003',
    name: '火山灰谷',
    chapter: 4,
    stageNumber: 3,
    description: '火山灰遮蔽了天空，能见度很低，需要小心前进。',
    background: 'ash_valley',
    difficulty: 1,
    enemyIds: ['ash_wraith_001'],
    enemyLevel: 1,
    isBossLevel: false,
    rewards: { exp: 75, gold: 150, memoryShards: 9 }
  },
  {
    id: 'ch4_stage_004',
    name: '地热喷泉',
    chapter: 4,
    stageNumber: 4,
    description: '地热喷泉不时喷出滚烫的水汽，要小心避开。',
    background: 'geyser_field',
    difficulty: 1,
    enemyIds: ['steam_spirit_001', 'ash_sprite_001'],
    enemyLevel: 1,
    isBossLevel: false,
    rewards: { exp: 80, gold: 160, memoryShards: 9 }
  },
  {
    id: 'ch4_stage_005',
    name: '熔岩裂缝',
    chapter: 4,
    stageNumber: 5,
    description: '地面上出现了熔岩裂缝，火红的光芒从裂缝中透出。',
    background: 'lava_crack',
    difficulty: 2,
    enemyIds: ['lava_maggot_001'],
    enemyLevel: 2,
    isBossLevel: false,
    rewards: { exp: 90, gold: 180, memoryShards: 10 }
  },
  {
    id: 'ch4_stage_006',
    name: '火焰呼吸',
    chapter: 4,
    stageNumber: 6,
    description: '空气变得炙热，每一次呼吸都像是在吸入火焰。',
    background: 'fire_breath',
    difficulty: 2,
    enemyIds: ['fire_breather_001'],
    enemyLevel: 2,
    isBossLevel: false,
    rewards: { exp: 95, gold: 190, memoryShards: 10 }
  },
  {
    id: 'ch4_stage_007',
    name: '黑曜石林',
    chapter: 4,
    stageNumber: 7,
    description: '黑色的黑曜石柱林立，它们是火山力量的结晶。',
    background: 'obsidian_forest',
    difficulty: 2,
    enemyIds: ['obsidian_shard_001', 'ash_wraith_001'],
    enemyLevel: 2,
    isBossLevel: false,
    rewards: { exp: 100, gold: 200, memoryShards: 11 }
  },
  {
    id: 'ch4_stage_008',
    name: '岩浆溪流',
    chapter: 4,
    stageNumber: 8,
    description: '岩浆形成的溪流缓缓流动，挡在前方的道路上。',
    background: 'lava_stream',
    difficulty: 2,
    enemyIds: ['lava_serpent_001'],
    enemyLevel: 2,
    isBossLevel: false,
    rewards: { exp: 105, gold: 210, memoryShards: 11 }
  },
  {
    id: 'ch4_stage_009',
    name: '灰烬风暴',
    chapter: 4,
    stageNumber: 9,
    description: '火山灰形成的风暴席卷而来，遮蔽了视线。',
    background: 'ash_storm',
    difficulty: 2,
    enemyIds: ['ash_storm_spirit_001', 'fire_breather_001'],
    enemyLevel: 2,
    isBossLevel: false,
    rewards: { exp: 110, gold: 220, memoryShards: 12 }
  },
  {
    id: 'ch4_stage_010',
    name: '熔岩守卫',
    chapter: 4,
    stageNumber: 10,
    description: '由岩浆构成的守卫挡住了去路，它散发着灼热的气息。',
    background: 'lava_guardian_gate',
    difficulty: 2,
    enemyIds: ['magma_guardian_001'],
    enemyLevel: 3,
    isBossLevel: true,
    rewards: { exp: 150, gold: 350, memoryShards: 22 }
  },
  // ========== 初级区域 (第11-20关) 难度2-3 ==========
  {
    id: 'ch4_stage_011',
    name: '火山斜坡',
    chapter: 4,
    stageNumber: 11,
    description: '开始向火山斜坡攀登，温度越来越高。',
    background: 'volcano_slope',
    difficulty: 2,
    enemyIds: ['slope_crawler_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 130, gold: 260, memoryShards: 13 }
  },
  {
    id: 'ch4_stage_012',
    name: '熔岩洞穴',
    chapter: 4,
    stageNumber: 12,
    description: '熔岩洞穴内部温度极高，墙壁散发着红光。',
    background: 'lava_cave',
    difficulty: 2,
    enemyIds: ['cave_lurker_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 135, gold: 270, memoryShards: 13 }
  },
  {
    id: 'ch4_stage_013',
    name: '火焰峡谷',
    chapter: 4,
    stageNumber: 13,
    description: '火焰峡谷中充满了易燃气体，随时可能爆发。',
    background: 'fire_canyon',
    difficulty: 2,
    enemyIds: ['fire_elemental_001', 'ash_sprite_003'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 140, gold: 280, memoryShards: 14 }
  },
  {
    id: 'ch4_stage_014',
    name: '火山地震',
    chapter: 4,
    stageNumber: 14,
    description: '地面剧烈震动，火山活动变得更加频繁。',
    background: 'volcano_quake',
    difficulty: 3,
    enemyIds: ['quake_spirit_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 150, gold: 300, memoryShards: 15 }
  },
  {
    id: 'ch4_stage_015',
    name: '熔岩瀑布',
    chapter: 4,
    stageNumber: 15,
    description: '岩浆形成瀑布从高处倾泻而下，壮观而危险。',
    background: 'lava_waterfall',
    difficulty: 3,
    enemyIds: ['waterfall_guardian_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 155, gold: 310, memoryShards: 15 }
  },
  {
    id: 'ch4_stage_016',
    name: '火山祭祀场',
    chapter: 4,
    stageNumber: 16,
    description: '古老的祭祀场遗迹，曾经有人在此祭祀火山之神。',
    background: 'volcano_shrine',
    difficulty: 3,
    enemyIds: ['shrine_ghost_001', 'fire_priest_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 160, gold: 320, memoryShards: 16 }
  },
  {
    id: 'ch4_stage_017',
    name: '硫磺湖',
    chapter: 4,
    stageNumber: 17,
    description: '一个巨大的硫磺湖，湖水翻滚着冒出有毒气体。',
    background: 'sulfur_lake',
    difficulty: 3,
    enemyIds: ['sulfur_beast_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 165, gold: 330, memoryShards: 16 }
  },
  {
    id: 'ch4_stage_018',
    name: '火山岩道',
    chapter: 4,
    stageNumber: 18,
    description: '被火山岩堵住的通道，只有最坚硬的路径可以通行。',
    background: 'lava_rock_path',
    difficulty: 3,
    enemyIds: ['rock_crawler_001', 'ash_wraith_002'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 170, gold: 340, memoryShards: 17 }
  },
  {
    id: 'ch4_stage_019',
    name: '火焰风暴',
    chapter: 4,
    stageNumber: 19,
    description: '火焰风暴席卷整个区域，空气中充满了火星。',
    background: 'fire_storm',
    difficulty: 3,
    enemyIds: ['fire_storm_wraith_001', 'fire_elemental_002'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 175, gold: 350, memoryShards: 17 }
  },
  {
    id: 'ch4_stage_020',
    name: '初级熔岩巨兽',
    chapter: 4,
    stageNumber: 20,
    description: '一只由岩浆和岩石构成的巨兽从地底苏醒。',
    background: 'junior_magma_beast_arena',
    difficulty: 3,
    enemyIds: ['magma_beast_junior_001'],
    enemyLevel: 4,
    isBossLevel: true,
    rewards: { exp: 240, gold: 550, memoryShards: 40 }
  },
  // ========== 中级区域 (第21-30关) 难度3-4 ==========
  {
    id: 'ch4_stage_021',
    name: '火山心脏',
    chapter: 4,
    stageNumber: 21,
    description: '到达火山的心脏地带，岩浆的脉动清晰可见。',
    background: 'volcano_heart',
    difficulty: 3,
    enemyIds: ['heart_sentinel_fire_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 190, gold: 380, memoryShards: 19 }
  },
  {
    id: 'ch4_stage_022',
    name: '熔岩墓地',
    chapter: 4,
    stageNumber: 22,
    description: '被火山吞噬的古代城市遗迹，埋葬着无数灵魂。',
    background: 'lava_graveyard',
    difficulty: 3,
    enemyIds: ['burnt_soul_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 195, gold: 390, memoryShards: 19 }
  },
  {
    id: 'ch4_stage_023',
    name: '火山熔炉',
    chapter: 4,
    stageNumber: 23,
    description: '古老的熔炉仍在运转，锻造着火焰武器。',
    background: 'volcano_forge',
    difficulty: 4,
    enemyIds: ['forge_master_001', 'fire_golem_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 205, gold: 410, memoryShards: 21 }
  },
  {
    id: 'ch4_stage_024',
    name: '岩浆河流',
    chapter: 4,
    stageNumber: 24,
    description: '宽阔的岩浆河流横亘在前方，必须找到方法穿越。',
    background: 'lava_river_wide',
    difficulty: 4,
    enemyIds: ['river_lava_beast_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 210, gold: 420, memoryShards: 21 }
  },
  {
    id: 'ch4_stage_025',
    name: '火山编织者',
    chapter: 4,
    stageNumber: 25,
    description: '一个神秘的存在正在编织岩浆，创造新的火焰生物。',
    background: 'fire_weaver_lair',
    difficulty: 4,
    enemyIds: ['fire_weaver_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 215, gold: 430, memoryShards: 22 }
  },
  {
    id: 'ch4_stage_026',
    name: '黑曜石宫殿',
    chapter: 4,
    stageNumber: 26,
    description: '一座由黑曜石建造的古老宫殿，散发着诡异的光芒。',
    background: 'obsidian_palace',
    difficulty: 4,
    enemyIds: ['obsidian_guardian_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 220, gold: 440, memoryShards: 22 }
  },
  {
    id: 'ch4_stage_027',
    name: '火山陷阱区',
    chapter: 4,
    stageNumber: 27,
    description: '火山活动形成了无数陷阱，喷发的岩浆随时可能到来。',
    background: 'volcano_trap_zone',
    difficulty: 4,
    enemyIds: ['trap_fire_spirit_001', 'hunter_ash_001', 'lava_serpent_002'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 225, gold: 450, memoryShards: 23 }
  },
  {
    id: 'ch4_stage_028',
    name: '火焰女王',
    chapter: 4,
    stageNumber: 28,
    description: '火焰洞穴的女王苏醒，她掌控着这片区域的火焰。',
    background: 'fire_queen_chamber',
    difficulty: 4,
    enemyIds: ['fire_queen_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 230, gold: 460, memoryShards: 23 }
  },
  {
    id: 'ch4_stage_029',
    name: '火山的觉醒',
    chapter: 4,
    stageNumber: 29,
    description: '火山本身似乎有了意识，它开始对你产生敌意。',
    background: 'awakened_volcano',
    difficulty: 4,
    enemyIds: ['volcano_eye_001', 'magma_core_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 235, gold: 470, memoryShards: 24 }
  },
  {
    id: 'ch4_stage_030',
    name: '中级熔岩巨兽',
    chapter: 4,
    stageNumber: 30,
    description: '一只巨大的火焰凤凰从岩浆中升起，它是火焰的化身。',
    background: 'mid_magma_beast_arena',
    difficulty: 4,
    enemyIds: ['magma_phoenix_001'],
    enemyLevel: 5,
    isBossLevel: true,
    rewards: { exp: 340, gold: 800, memoryShards: 58 }
  },
  // ========== 高级区域 (第31-40关) 难度4-5 ==========
  {
    id: 'ch4_stage_031',
    name: '火山深渊',
    chapter: 4,
    stageNumber: 31,
    description: '深入火山最危险的深渊，这里是岩浆的源头。',
    background: 'volcano_abyss',
    difficulty: 4,
    enemyIds: ['abyss_fire_horror_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 250, gold: 500, memoryShards: 26 }
  },
  {
    id: 'ch4_stage_032',
    name: '破碎的熔岩',
    chapter: 4,
    stageNumber: 32,
    description: '破碎的熔岩板块四处漂浮，每一步都充满危险。',
    background: 'shattered_lava',
    difficulty: 4,
    enemyIds: ['lava_shard_beast_001', 'plate_guardian_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 255, gold: 510, memoryShards: 26 }
  },
  {
    id: 'ch4_stage_033',
    name: '愤怒的熔岩',
    chapter: 4,
    stageNumber: 33,
    description: '熔岩对你的入侵感到愤怒，它开始狂暴地喷发。',
    background: 'angry_lava',
    difficulty: 5,
    enemyIds: ['angry_magma_titan_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 270, gold: 540, memoryShards: 28 }
  },
  {
    id: 'ch4_stage_034',
    name: '火焰囚牢',
    chapter: 4,
    stageNumber: 34,
    description: '被困的火焰灵魂被囚禁在此，它们渴望自由却充满敌意。',
    background: 'fire_prison',
    difficulty: 5,
    enemyIds: ['imprisoned_flame_001', 'fire_warden_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 275, gold: 550, memoryShards: 28 }
  },
  {
    id: 'ch4_stage_035',
    name: '无限熔岩',
    chapter: 4,
    stageNumber: 35,
    description: '一片似乎没有尽头的熔岩海，只有火焰存在。',
    background: 'infinite_lava_sea',
    difficulty: 5,
    enemyIds: ['lava_sea_phantom_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 280, gold: 560, memoryShards: 29 }
  },
  {
    id: 'ch4_stage_036',
    name: '古老火山口',
    chapter: 4,
    stageNumber: 36,
    description: '一个古老的火山口，封印着远古时代的火焰生物。',
    background: 'ancient_crater',
    difficulty: 5,
    enemyIds: ['ancient_fire_being_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 285, gold: 570, memoryShards: 29 }
  },
  {
    id: 'ch4_stage_037',
    name: '火山意志',
    chapter: 4,
    stageNumber: 37,
    description: '火山凝聚出了自己的意志，它要毁灭所有入侵者。',
    background: 'will_of_volcano',
    difficulty: 5,
    enemyIds: ['volcano_will_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 290, gold: 580, memoryShards: 30 }
  },
  {
    id: 'ch4_stage_038',
    name: '岩浆漩涡',
    chapter: 4,
    stageNumber: 38,
    description: '一个巨大的岩浆漩涡正在形成，吞噬着周围的一切。',
    background: 'lava_vortex',
    difficulty: 5,
    enemyIds: ['vortex_guardian_fire_001', 'sucked_magma_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 295, gold: 590, memoryShards: 30 }
  },
  {
    id: 'ch4_stage_039',
    name: '最后的攀登',
    chapter: 4,
    stageNumber: 39,
    description: '进入精英区域前的最后攀登，接近火山的顶峰。',
    background: 'final_ascent',
    difficulty: 5,
    enemyIds: ['ascent_sentinel_001', 'peak_guardian_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 300, gold: 600, memoryShards: 31 }
  },
  {
    id: 'ch4_stage_040',
    name: '高级熔岩巨兽',
    chapter: 4,
    stageNumber: 40,
    description: '一只巨大的熔岩龙从火山深处升起，它是这片区域的终极守护者。',
    background: 'high_magma_beast_arena',
    difficulty: 5,
    enemyIds: ['magma_dragon_001'],
    enemyLevel: 6,
    isBossLevel: true,
    rewards: { exp: 420, gold: 980, memoryShards: 82 }
  },
  // ========== 精英区域 (第41-49关) 难度5 ==========
  {
    id: 'ch4_stage_041',
    name: '火山核心',
    chapter: 4,
    stageNumber: 41,
    description: '精英区域的起始，火山的核心地带，岩浆翻腾。',
    background: 'volcano_core',
    difficulty: 5,
    enemyIds: ['core_fire_defender_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 320, gold: 640, memoryShards: 32 }
  },
  {
    id: 'ch4_stage_042',
    name: '熔岩王座',
    chapter: 4,
    stageNumber: 42,
    description: '一座由岩浆构成的王座，散发着毁灭性的力量。',
    background: 'lava_throne',
    difficulty: 5,
    enemyIds: ['throne_usurper_fire_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 325, gold: 650, memoryShards: 32 }
  },
  {
    id: 'ch4_stage_043',
    name: '无尽熔岩',
    chapter: 4,
    stageNumber: 43,
    description: '熔岩似乎没有边界，延伸到无限的远方。',
    background: 'endless_lava_zone',
    difficulty: 5,
    enemyIds: ['infinite_lava_entity_001', 'fire_lord_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 330, gold: 660, memoryShards: 33 }
  },
  {
    id: 'ch4_stage_044',
    name: '火山之源',
    chapter: 4,
    stageNumber: 44,
    description: '所有火山力量的源头，一个古老而强大的存在守护着这里。',
    background: 'source_of_volcano',
    difficulty: 5,
    enemyIds: ['volcano_source_guardian_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 335, gold: 670, memoryShards: 33 }
  },
  {
    id: 'ch4_stage_045',
    name: '岩浆典狱长',
    chapter: 4,
    stageNumber: 45,
    description: '这片火山区域的典狱长，掌控着岩浆与火焰的规则。',
    background: 'lava_warden_chamber',
    difficulty: 5,
    enemyIds: ['lava_warden_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 340, gold: 680, memoryShards: 34 }
  },
  {
    id: 'ch4_stage_046',
    name: '禁忌熔岩',
    chapter: 4,
    stageNumber: 46,
    description: '禁忌的熔岩被封印在此，任何触碰都可能万劫不复。',
    background: 'forbidden_lava',
    difficulty: 5,
    enemyIds: ['forbidden_fire_keeper_001', 'cursed_phoenix_001'],
    enemyLevel: 7,
    isBossLevel: false,
    rewards: { exp: 345, gold: 690, memoryShards: 34 }
  },
  {
    id: 'ch4_stage_047',
    name: '火山的真相',
    chapter: 4,
    stageNumber: 47,
    description: '开始接近火山的真相，守卫变得更加疯狂而强大。',
    background: 'truth_of_volcano_chamber',
    difficulty: 5,
    enemyIds: ['volcano_truth_guardian_001'],
    enemyLevel: 7,
    isBossLevel: false,
    rewards: { exp: 350, gold: 700, memoryShards: 35 }
  },
  {
    id: 'ch4_stage_048',
    name: '火山巅峰',
    chapter: 4,
    stageNumber: 48,
    description: '普通火山的巅峰，在这里你将面对最强大的火焰生物。',
    background: 'peak_of_volcano',
    difficulty: 5,
    enemyIds: ['peak_fire_being_001'],
    enemyLevel: 7,
    isBossLevel: false,
    rewards: { exp: 355, gold: 710, memoryShards: 35 }
  },
  {
    id: 'ch4_stage_049',
    name: '终极火山守卫',
    chapter: 4,
    stageNumber: 49,
    description: '精英区域的最终守卫，击败它才能面对章节Boss。',
    background: 'ultimate_volcano_gate',
    difficulty: 5,
    enemyIds: ['ultimate_fire_sentinel_001', 'ultimate_lava_defender_001'],
    enemyLevel: 7,
    isBossLevel: false,
    rewards: { exp: 360, gold: 720, memoryShards: 36 }
  },
  // ========== 章节Boss (第50关) 难度6 ==========
  {
    id: 'ch4_stage_050',
    name: '火山之主',
    chapter: 4,
    stageNumber: 50,
    description: '愤怒火山的真正主宰，它是火焰与岩浆的化身，掌控着毁灭与重生的力量。它能召唤岩浆爆发，创造新的火焰生物。只有战胜它，才能平息火山的愤怒。',
    background: 'lord_of_volcano_throne',
    difficulty: 6,
    enemyIds: ['volcano_overlord_001'],
    enemyLevel: 8,
    isBossLevel: true,
    rewards: { exp: 650, gold: 1800, memoryShards: 160 }
  }
];

export default Chapter4Stages;
