import { LevelConfig } from './LevelTypes';

/**
 * 第2章：遗忘之境 (Chapter 2: The Realm of Oblivion)
 * 主题：被遗忘的记忆，朦胧的雾气，失落的片段
 * 风格：灰白迷雾，若隐若现的轮廓，朦胧感
 */

export const Chapter2Stages: LevelConfig[] = [
  // ========== 教学/入门区域 (第1-10关) 难度1-2 ==========
  {
    id: 'ch2_stage_001',
    name: '迷雾初临',
    chapter: 2,
    stageNumber: 1,
    description: '浓重的迷雾笼罩着这片土地，你几乎看不见前方的路。',
    background: 'misty_entrance',
    difficulty: 1,
    enemyIds: ['fog_wisp_001'],
    enemyLevel: 1,
    isBossLevel: false,
    rewards: { exp: 55, gold: 110, memoryShards: 6 }
  },
  {
    id: 'ch2_stage_002',
    name: '失落的足迹',
    chapter: 2,
    stageNumber: 2,
    description: '地面上有模糊的足迹，但很快就被迷雾吞没。',
    background: 'fading_trails',
    difficulty: 1,
    enemyIds: ['fog_wisp_001', 'fog_wisp_002'],
    enemyLevel: 1,
    isBossLevel: false,
    rewards: { exp: 60, gold: 120, memoryShards: 6 }
  },
  {
    id: 'ch2_stage_003',
    name: '残影徘徊',
    chapter: 2,
    stageNumber: 3,
    description: '模糊的身影在雾中徘徊，那是被遗忘者的幽灵。',
    background: 'wandering_shadows',
    difficulty: 1,
    enemyIds: ['forgotten_shadow_001'],
    enemyLevel: 1,
    isBossLevel: false,
    rewards: { exp: 65, gold: 130, memoryShards: 7 }
  },
  {
    id: 'ch2_stage_004',
    name: '模糊的记忆',
    chapter: 2,
    stageNumber: 4,
    description: '一些记忆开始变得模糊，仿佛从未存在过。',
    background: 'blurry_memory_field',
    difficulty: 1,
    enemyIds: ['blur_sprite_001', 'fog_wisp_001'],
    enemyLevel: 1,
    isBossLevel: false,
    rewards: { exp: 70, gold: 140, memoryShards: 7 }
  },
  {
    id: 'ch2_stage_005',
    name: '褪色画卷',
    chapter: 2,
    stageNumber: 5,
    description: '周围的景象如同褪色的画卷，渐渐失去色彩。',
    background: 'faded_painting',
    difficulty: 2,
    enemyIds: ['fading_artist_001'],
    enemyLevel: 2,
    isBossLevel: false,
    rewards: { exp: 80, gold: 160, memoryShards: 8 }
  },
  {
    id: 'ch2_stage_006',
    name: '遗忘之息',
    chapter: 2,
    stageNumber: 6,
    description: '空气中弥漫着遗忘的气息，让你的思维变得迟钝。',
    background: 'oblivion_breath',
    difficulty: 2,
    enemyIds: ['oblivion_mist_001'],
    enemyLevel: 2,
    isBossLevel: false,
    rewards: { exp: 85, gold: 170, memoryShards: 8 }
  },
  {
    id: 'ch2_stage_007',
    name: '消散的轮廓',
    chapter: 2,
    stageNumber: 7,
    description: '物体的轮廓开始变得不清晰，仿佛随时会消失。',
    background: 'dissolving_forms',
    difficulty: 2,
    enemyIds: ['dissolving_form_001', 'fog_wisp_002'],
    enemyLevel: 2,
    isBossLevel: false,
    rewards: { exp: 90, gold: 180, memoryShards: 9 }
  },
  {
    id: 'ch2_stage_008',
    name: '无名之地',
    chapter: 2,
    stageNumber: 8,
    description: '这是一片无名之地，连地名都已被遗忘。',
    background: 'nameless_land',
    difficulty: 2,
    enemyIds: ['nameless_spirit_001'],
    enemyLevel: 2,
    isBossLevel: false,
    rewards: { exp: 95, gold: 190, memoryShards: 9 }
  },
  {
    id: 'ch2_stage_009',
    name: '迷失者聚集',
    chapter: 2,
    stageNumber: 9,
    description: '迷失的灵魂在此聚集，它们忘记了归途。',
    background: 'lost_souls_gathering',
    difficulty: 2,
    enemyIds: ['lost_soul_001', 'lost_soul_002'],
    enemyLevel: 2,
    isBossLevel: false,
    rewards: { exp: 100, gold: 200, memoryShards: 10 }
  },
  {
    id: 'ch2_stage_010',
    name: '迷雾守卫',
    chapter: 2,
    stageNumber: 10,
    description: '迷雾凝聚成守卫，阻挡着入侵者的脚步。',
    background: 'mist_guardian_gate',
    difficulty: 2,
    enemyIds: ['mist_guardian_001'],
    enemyLevel: 3,
    isBossLevel: true,
    rewards: { exp: 130, gold: 280, memoryShards: 18 }
  },
  // ========== 初级区域 (第11-20关) 难度2-3 ==========
  {
    id: 'ch2_stage_011',
    name: '深入迷雾',
    chapter: 2,
    stageNumber: 11,
    description: '迷雾变得更加浓厚，能见度不足三米。',
    background: 'deep_mist',
    difficulty: 2,
    enemyIds: ['deep_fog_entity_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 110, gold: 220, memoryShards: 11 }
  },
  {
    id: 'ch2_stage_012',
    name: '记忆的裂痕',
    chapter: 2,
    stageNumber: 12,
    description: '记忆中出现了裂痕，有些片段正在漏失。',
    background: 'memory_crack',
    difficulty: 2,
    enemyIds: ['memory_leak_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 115, gold: 230, memoryShards: 11 }
  },
  {
    id: 'ch2_stage_013',
    name: '空白之页',
    chapter: 2,
    stageNumber: 13,
    description: '一本空白的书漂浮在空中，书页正等待被填满。',
    background: 'blank_page',
    difficulty: 2,
    enemyIds: ['blank_scriptor_001', 'fog_wisp_003'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 120, gold: 240, memoryShards: 12 }
  },
  {
    id: 'ch2_stage_014',
    name: '消逝的回声',
    chapter: 2,
    stageNumber: 14,
    description: '回声越来越微弱，仿佛正在被遗忘吞噬。',
    background: 'fading_echo',
    difficulty: 3,
    enemyIds: ['fading_echo_wraith_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 130, gold: 260, memoryShards: 13 }
  },
  {
    id: 'ch2_stage_015',
    name: '无名墓碑',
    chapter: 2,
    stageNumber: 15,
    description: '一座无名的墓碑矗立在雾中，上面刻着的名字已被风化。',
    background: 'nameless_grave',
    difficulty: 3,
    enemyIds: ['grave_spirit_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 135, gold: 270, memoryShards: 13 }
  },
  {
    id: 'ch2_stage_016',
    name: '褪色的面孔',
    chapter: 2,
    stageNumber: 16,
    description: '你看到一些面孔，但它们的面容正在迅速褪色。',
    background: 'fading_faces',
    difficulty: 3,
    enemyIds: ['faceless_memory_001', 'fading_face_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 140, gold: 280, memoryShards: 14 }
  },
  {
    id: 'ch2_stage_017',
    name: '遗忘的河流',
    chapter: 2,
    stageNumber: 17,
    description: '一条河流静静流淌，河水似乎能洗去记忆。',
    background: 'river_of_forgetting',
    difficulty: 3,
    enemyIds: ['river_spirit_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 145, gold: 290, memoryShards: 14 }
  },
  {
    id: 'ch2_stage_018',
    name: '模糊的路径',
    chapter: 2,
    stageNumber: 18,
    description: '前方的道路变得模糊不清，难以辨认方向。',
    background: 'blurry_path',
    difficulty: 3,
    enemyIds: ['path_blocker_001', 'fog_wisp_004'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 150, gold: 300, memoryShards: 15 }
  },
  {
    id: 'ch2_stage_019',
    name: '记忆的碎片',
    chapter: 2,
    stageNumber: 19,
    description: '零散的记忆碎片在雾中漂浮，但无法拼凑成完整的画面。',
    background: 'memory_fragments_field',
    difficulty: 3,
    enemyIds: ['fragment_collector_001', 'lost_soul_003'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 155, gold: 310, memoryShards: 15 }
  },
  {
    id: 'ch2_stage_020',
    name: '初级遗忘者',
    chapter: 2,
    stageNumber: 20,
    description: '一个被遗忘的存在苏醒，它要守护这片遗忘之地。',
    background: 'junior_forgetter_arena',
    difficulty: 3,
    enemyIds: ['junior_forgetter_001'],
    enemyLevel: 4,
    isBossLevel: true,
    rewards: { exp: 200, gold: 450, memoryShards: 30 }
  },
  // ========== 中级区域 (第21-30关) 难度3-4 ==========
  {
    id: 'ch2_stage_021',
    name: '迷雾之心',
    chapter: 2,
    stageNumber: 21,
    description: '到达迷雾的核心地带，遗忘的力量达到了新的高度。',
    background: 'mist_heart',
    difficulty: 3,
    enemyIds: ['mist_heart_sentinel_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 165, gold: 330, memoryShards: 16 }
  },
  {
    id: 'ch2_stage_022',
    name: '记忆的坟墓',
    chapter: 2,
    stageNumber: 22,
    description: '无数被埋葬的记忆在这里沉睡，但有些不愿安息。',
    background: 'memory_graveyard',
    difficulty: 3,
    enemyIds: ['memory_ghost_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 170, gold: 340, memoryShards: 16 }
  },
  {
    id: 'ch2_stage_023',
    name: '消逝的画廊',
    chapter: 2,
    stageNumber: 23,
    description: '画廊中的画像正在消逝，画中人的面容已不可辨认。',
    background: 'fading_gallery',
    difficulty: 4,
    enemyIds: ['gallery_apparition_001', 'painting_ghost_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 180, gold: 360, memoryShards: 18 }
  },
  {
    id: 'ch2_stage_024',
    name: '遗忘的喷泉',
    chapter: 2,
    stageNumber: 24,
    description: '一座古老的喷泉，喷出的水雾能让记忆流失。',
    background: 'fountain_of_forgetting',
    difficulty: 4,
    enemyIds: ['fountain_guardian_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 185, gold: 370, memoryShards: 18 }
  },
  {
    id: 'ch2_stage_025',
    name: '迷雾编织者',
    chapter: 2,
    stageNumber: 25,
    description: '一个神秘的存在正在编织迷雾，创造新的遗忘。',
    background: 'mist_weaver_chamber',
    difficulty: 4,
    enemyIds: ['mist_weaver_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 190, gold: 380, memoryShards: 19 }
  },
  {
    id: 'ch2_stage_026',
    name: '无名的城市',
    chapter: 2,
    stageNumber: 26,
    description: '一座被遗忘的城市，连它的名字都已消失在历史中。',
    background: 'nameless_city',
    difficulty: 4,
    enemyIds: ['city_apparition_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 195, gold: 390, memoryShards: 19 }
  },
  {
    id: 'ch2_stage_027',
    name: '记忆的陷阱',
    chapter: 2,
    stageNumber: 27,
    description: '遗忘之地布满了陷阱，让你的记忆不断流失。',
    background: 'memory_trap_zone',
    difficulty: 4,
    enemyIds: ['trap_spirit_001', 'trap_spirit_002', 'fog_wisp_005'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 200, gold: 400, memoryShards: 20 }
  },
  {
    id: 'ch2_stage_028',
    name: '过去的灰烬',
    chapter: 2,
    stageNumber: 28,
    description: '曾经辉煌的过去，如今只剩下灰烬和回忆。',
    background: 'ashes_of_past',
    difficulty: 4,
    enemyIds: ['ash_memory_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 205, gold: 410, memoryShards: 20 }
  },
  {
    id: 'ch2_stage_029',
    name: '遗忘的觉醒',
    chapter: 2,
    stageNumber: 29,
    description: '遗忘本身开始觉醒，它意识到了你的存在。',
    background: 'awakened_oblivion',
    difficulty: 4,
    enemyIds: ['oblivion_eye_001', 'deep_fog_entity_002'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 210, gold: 420, memoryShards: 21 }
  },
  {
    id: 'ch2_stage_030',
    name: '中级遗忘者',
    chapter: 2,
    stageNumber: 30,
    description: '中级区域的遗忘之主降临，它掌握着更深层的遗忘之力。',
    background: 'mid_forgetter_arena',
    difficulty: 4,
    enemyIds: ['mid_forgetter_001'],
    enemyLevel: 5,
    isBossLevel: true,
    rewards: { exp: 280, gold: 620, memoryShards: 42 }
  },
  // ========== 高级区域 (第31-40关) 难度4-5 ==========
  {
    id: 'ch2_stage_031',
    name: '深渊迷雾',
    chapter: 2,
    stageNumber: 31,
    description: '深入最浓重的迷雾，这里的遗忘几乎是绝对的。',
    background: 'abyssal_mist',
    difficulty: 4,
    enemyIds: ['abyss_fog_horror_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 220, gold: 440, memoryShards: 22 }
  },
  {
    id: 'ch2_stage_032',
    name: '碎裂的自我',
    chapter: 2,
    stageNumber: 32,
    description: '你的记忆开始出现裂痕，自我认同变得模糊。',
    background: 'fractured_self_memory',
    difficulty: 4,
    enemyIds: ['self_fragment_ghost_001', 'identity_thief_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 225, gold: 450, memoryShards: 22 }
  },
  {
    id: 'ch2_stage_033',
    name: '愤怒的遗忘',
    chapter: 2,
    stageNumber: 33,
    description: '被遗忘的记忆充满了愤怒，它们不愿被忽视。',
    background: 'angry_oblivion',
    difficulty: 5,
    enemyIds: ['angry_forgotten_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 240, gold: 480, memoryShards: 24 }
  },
  {
    id: 'ch2_stage_034',
    name: '记忆的囚牢',
    chapter: 2,
    stageNumber: 34,
    description: '某些记忆被囚禁在此，它们被遗忘却又不被释放。',
    background: 'memory_prison_oblivion',
    difficulty: 5,
    enemyIds: ['imprisoned_memory_002', 'prison_keeper_fog_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 245, gold: 490, memoryShards: 24 }
  },
  {
    id: 'ch2_stage_035',
    name: '无限迷雾',
    chapter: 2,
    stageNumber: 35,
    description: '迷雾似乎没有尽头，无论怎么走都在原地打转。',
    background: 'infinite_mist',
    difficulty: 5,
    enemyIds: ['mist_loop_phantom_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 250, gold: 500, memoryShards: 25 }
  },
  {
    id: 'ch2_stage_036',
    name: '古老的遗忘',
    chapter: 2,
    stageNumber: 36,
    description: '这里封印着最古老的遗忘，连时间都无法触及。',
    background: 'ancient_oblivion',
    difficulty: 5,
    enemyIds: ['ancient_forgotten_one_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 255, gold: 510, memoryShards: 25 }
  },
  {
    id: 'ch2_stage_037',
    name: '遗忘的意志',
    chapter: 2,
    stageNumber: 37,
    description: '遗忘凝聚出了自己的意志，它在抵抗你的前进。',
    background: 'will_of_oblivion',
    difficulty: 5,
    enemyIds: ['oblivion_will_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 260, gold: 520, memoryShards: 26 }
  },
  {
    id: 'ch2_stage_038',
    name: '记忆的漩涡',
    chapter: 2,
    stageNumber: 38,
    description: '一个由流失记忆组成的漩涡，吞噬着一切进入其中的东西。',
    background: 'memory_vortex_oblivion',
    difficulty: 5,
    enemyIds: ['vortex_guardian_002', 'sucked_memory_ghost_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 265, gold: 530, memoryShards: 26 }
  },
  {
    id: 'ch2_stage_039',
    name: '最后的试炼',
    chapter: 2,
    stageNumber: 39,
    description: '进入精英区域前的最终试炼，你必须抵抗深层的遗忘。',
    background: 'final_trial_chamber',
    difficulty: 5,
    enemyIds: ['trial_sentinel_fog_001', 'trial_sentinel_fog_002'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 270, gold: 540, memoryShards: 27 }
  },
  {
    id: 'ch2_stage_040',
    name: '高级遗忘者',
    chapter: 2,
    stageNumber: 40,
    description: '高级区域的遗忘之主现身，它的力量足以抹去任何记忆。',
    background: 'high_forgetter_arena',
    difficulty: 5,
    enemyIds: ['high_forgetter_001'],
    enemyLevel: 6,
    isBossLevel: true,
    rewards: { exp: 350, gold: 780, memoryShards: 60 }
  },
  // ========== 精英区域 (第41-49关) 难度5 ==========
  {
    id: 'ch2_stage_041',
    name: '遗忘核心',
    chapter: 2,
    stageNumber: 41,
    description: '精英区域的起始，遗忘的核心地带，雾气最为浓重。',
    background: 'oblivion_core',
    difficulty: 5,
    enemyIds: ['core_fog_defender_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 280, gold: 560, memoryShards: 28 }
  },
  {
    id: 'ch2_stage_042',
    name: '无主之座',
    chapter: 2,
    stageNumber: 42,
    description: '一座无人知晓主人的王座，散发着淡淡的遗忘气息。',
    background: 'ownerless_throne',
    difficulty: 5,
    enemyIds: ['throne_usurper_fog_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 285, gold: 570, memoryShards: 28 }
  },
  {
    id: 'ch2_stage_043',
    name: '无尽的迷雾',
    chapter: 2,
    stageNumber: 43,
    description: '迷雾似乎没有边界，延伸到无限的远方。',
    background: 'endless_mist_zone',
    difficulty: 5,
    enemyIds: ['infinite_mist_entity_001', 'mist_lord_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 290, gold: 580, memoryShards: 29 }
  },
  {
    id: 'ch2_stage_044',
    name: '遗忘之源',
    chapter: 2,
    stageNumber: 44,
    description: '所有遗忘的源头，一个古老而强大的存在守护着这里。',
    background: 'source_of_oblivion',
    difficulty: 5,
    enemyIds: ['oblivion_source_guardian_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 295, gold: 590, memoryShards: 29 }
  },
  {
    id: 'ch2_stage_045',
    name: '迷雾的典狱长',
    chapter: 2,
    stageNumber: 45,
    description: '这片遗忘之地的典狱长，掌控着迷雾与遗忘的规则。',
    background: 'mist_warden_chamber',
    difficulty: 5,
    enemyIds: ['mist_warden_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 300, gold: 600, memoryShards: 30 }
  },
  {
    id: 'ch2_stage_046',
    name: '禁忌遗忘',
    chapter: 2,
    stageNumber: 46,
    description: '禁忌的遗忘被封印在此，任何触碰都可能万劫不复。',
    background: 'forbidden_oblivion',
    difficulty: 5,
    enemyIds: ['forbidden_oblivion_keeper_001', 'cursed_fog_001'],
    enemyLevel: 7,
    isBossLevel: false,
    rewards: { exp: 305, gold: 610, memoryShards: 30 }
  },
  {
    id: 'ch2_stage_047',
    name: '遗忘的真相',
    chapter: 2,
    stageNumber: 47,
    description: '开始接近遗忘之地的真相，守卫变得更加疯狂。',
    background: 'truth_of_oblivion_chamber',
    difficulty: 5,
    enemyIds: ['oblivion_truth_guardian_001'],
    enemyLevel: 7,
    isBossLevel: false,
    rewards: { exp: 310, gold: 620, memoryShards: 31 }
  },
  {
    id: 'ch2_stage_048',
    name: '遗忘的巅峰',
    chapter: 2,
    stageNumber: 48,
    description: '普通遗忘的巅峰，在这里你将面对最强大的遗忘体。',
    background: 'peak_of_oblivion',
    difficulty: 5,
    enemyIds: ['peak_oblivion_being_001'],
    enemyLevel: 7,
    isBossLevel: false,
    rewards: { exp: 315, gold: 630, memoryShards: 31 }
  },
  {
    id: 'ch2_stage_049',
    name: '终极守卫者',
    chapter: 2,
    stageNumber: 49,
    description: '精英区域的最终守卫，击败它才能面对章节Boss。',
    background: 'ultimate_oblivion_gate',
    difficulty: 5,
    enemyIds: ['ultimate_oblivion_sentinel_001', 'ultimate_fog_defender_001'],
    enemyLevel: 7,
    isBossLevel: false,
    rewards: { exp: 320, gold: 640, memoryShards: 32 }
  },
  // ========== 章节Boss (第50关) 难度6 ==========
  {
    id: 'ch2_stage_050',
    name: '遗忘之主',
    chapter: 2,
    stageNumber: 50,
    description: '遗忘之境的真正主宰，掌控着所有被遗忘的记忆。它能轻易抹去任何存在的痕迹，让一切回归虚无。只有战胜它，才能找回失去的记忆。',
    background: 'lord_of_oblivion_throne',
    difficulty: 6,
    enemyIds: ['lord_of_oblivion_001'],
    enemyLevel: 8,
    isBossLevel: true,
    rewards: { exp: 550, gold: 1400, memoryShards: 120 }
  }
];

export default Chapter2Stages;
