import { LevelConfig } from './LevelTypes';

/**
 * 第8章：命运交织 (Chapter 8: Fate Interweaving)
 * 主题：命运的丝线交织，因果轮回，时空交错
 * 风格：命运之线，时空裂缝，轮回之光
 */

export const Chapter8Stages: LevelConfig[] = [
  // ========== 教学/入门区域 (第1-10关) 难度1-2 ==========
  {
    id: 'ch8_stage_001',
    name: '命运之门',
    chapter: 8,
    stageNumber: 1,
    description: '命运的大门在前方展开，无数丝线在空中交织。',
    background: 'fate_gate',
    difficulty: 1,
    enemyIds: ['thread_wisp_001'],
    enemyLevel: 1,
    isBossLevel: false,
    rewards: { exp: 85, gold: 170, memoryShards: 12 }
  },
  {
    id: 'ch8_stage_002',
    name: '丝线回廊',
    chapter: 8,
    stageNumber: 2,
    description: '走廊中布满了闪烁的命运之线，指引着不同的未来。',
    background: 'thread_corridor',
    difficulty: 1,
    enemyIds: ['thread_wisp_001', 'thread_wisp_002'],
    enemyLevel: 1,
    isBossLevel: false,
    rewards: { exp: 90, gold: 180, memoryShards: 12 }
  },
  {
    id: 'ch8_stage_003',
    name: '因果之间',
    chapter: 8,
    stageNumber: 3,
    description: '这里展示着因果关系，每一个行动都会产生相应的结果。',
    background: 'karma_chamber',
    difficulty: 1,
    enemyIds: ['karma_spirit_001'],
    enemyLevel: 1,
    isBossLevel: false,
    rewards: { exp: 95, gold: 190, memoryShards: 13 }
  },
  {
    id: 'ch8_stage_004',
    name: '时空碎片',
    chapter: 8,
    stageNumber: 4,
    description: '破碎的时空片段漂浮在空中，展示着不同的可能性。',
    background: 'time_space_fragments',
    difficulty: 1,
    enemyIds: ['time_fragment_001', 'thread_wisp_001'],
    enemyLevel: 1,
    isBossLevel: false,
    rewards: { exp: 100, gold: 200, memoryShards: 13 }
  },
  {
    id: 'ch8_stage_005',
    name: '命运分叉',
    chapter: 8,
    stageNumber: 5,
    description: '命运之路在此分叉，选择将决定你的未来。',
    background: 'fate_crossroad',
    difficulty: 2,
    enemyIds: ['crossroad_guardian_001'],
    enemyLevel: 2,
    isBossLevel: false,
    rewards: { exp: 110, gold: 220, memoryShards: 14 }
  },
  {
    id: 'ch8_stage_006',
    name: '轮回之厅',
    chapter: 8,
    stageNumber: 6,
    description: '生命的轮回在这里展现，过去与未来在此交汇。',
    background: 'reincarnation_hall',
    difficulty: 2,
    enemyIds: ['cycle_ghost_001'],
    enemyLevel: 2,
    isBossLevel: false,
    rewards: { exp: 115, gold: 230, memoryShards: 14 }
  },
  {
    id: 'ch8_stage_007',
    name: '编织之台',
    chapter: 8,
    stageNumber: 7,
    description: '命运正在被编织，每一根丝线都代表着一个生命。',
    background: 'weaving_platform',
    difficulty: 2,
    enemyIds: ['loom_spirit_001', 'thread_wisp_002'],
    enemyLevel: 2,
    isBossLevel: false,
    rewards: { exp: 120, gold: 240, memoryShards: 15 }
  },
  {
    id: 'ch8_stage_008',
    name: '预言之间',
    chapter: 8,
    stageNumber: 8,
    description: '古老的预言在这里回响，诉说着注定的未来。',
    background: 'prophecy_chamber',
    difficulty: 2,
    enemyIds: ['prophecy_wraith_001'],
    enemyLevel: 2,
    isBossLevel: false,
    rewards: { exp: 125, gold: 250, memoryShards: 15 }
  },
  {
    id: 'ch8_stage_009',
    name: '宿命漩涡',
    chapter: 8,
    stageNumber: 9,
    description: '命运的漩涡在转动，将一切卷入注定的轨迹。',
    background: 'fate_vortex',
    difficulty: 2,
    enemyIds: ['destiny_mist_001', 'karma_spirit_001'],
    enemyLevel: 2,
    isBossLevel: false,
    rewards: { exp: 130, gold: 260, memoryShards: 16 }
  },
  {
    id: 'ch8_stage_010',
    name: '命运守卫',
    chapter: 8,
    stageNumber: 10,
    description: '守护命运之门的强大存在，不会轻易让外人通过。',
    background: 'fate_guardian_gate',
    difficulty: 2,
    enemyIds: ['fate_guardian_001'],
    enemyLevel: 3,
    isBossLevel: true,
    rewards: { exp: 190, gold: 480, memoryShards: 30 }
  },
  // ========== 初级区域 (第11-20关) 难度2-3 ==========
  {
    id: 'ch8_stage_011',
    name: '深入命运',
    chapter: 8,
    stageNumber: 11,
    description: '开始向命运的深处探索，丝线变得更加密集。',
    background: 'deep_fate',
    difficulty: 2,
    enemyIds: ['deep_thread_entity_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 170, gold: 340, memoryShards: 17 }
  },
  {
    id: 'ch8_stage_012',
    name: '时间裂隙',
    chapter: 8,
    stageNumber: 12,
    description: '时间的裂隙中可以看到过去与未来的片段。',
    background: 'time_rift',
    difficulty: 2,
    enemyIds: ['time_anomaly_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 175, gold: 350, memoryShards: 17 }
  },
  {
    id: 'ch8_stage_013',
    name: '命运洞穴',
    chapter: 8,
    stageNumber: 13,
    description: '洞穴中回响着命运的声音，讲述着无数生命的轨迹。',
    background: 'fate_cave',
    difficulty: 2,
    enemyIds: ['cave_fate_keeper_001', 'thread_wisp_003'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 180, gold: 360, memoryShards: 18 }
  },
  {
    id: 'ch8_stage_014',
    name: '因果暗流',
    chapter: 8,
    stageNumber: 14,
    description: '看不见的因果暗流在涌动，影响着每一个选择。',
    background: 'karma_current',
    difficulty: 3,
    enemyIds: ['current_karma_wraith_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 190, gold: 380, memoryShards: 19 }
  },
  {
    id: 'ch8_stage_015',
    name: '古老预言',
    chapter: 8,
    stageNumber: 15,
    description: '古老的预言刻在石壁上，预言着你的到来。',
    background: 'ancient_prophecy',
    difficulty: 3,
    enemyIds: ['ancient_prophet_ghost_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 195, gold: 390, memoryShards: 19 }
  },
  {
    id: 'ch8_stage_016',
    name: '轮回墓地',
    chapter: 8,
    stageNumber: 16,
    description: '这里埋葬着无数次轮回的记忆，逝者在此徘徊。',
    background: 'reincarnation_graveyard',
    difficulty: 3,
    enemyIds: ['reincarnation_ghost_001', 'cycled_soul_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 200, gold: 400, memoryShards: 20 }
  },
  {
    id: 'ch8_stage_017',
    name: '命运之泉',
    chapter: 8,
    stageNumber: 17,
    description: '喷涌的泉水映照着无数命运的片段。',
    background: 'fate_spring',
    difficulty: 3,
    enemyIds: ['spring_fate_spirit_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 205, gold: 410, memoryShards: 20 }
  },
  {
    id: 'ch8_stage_018',
    name: '时空深渊',
    chapter: 8,
    stageNumber: 18,
    description: '时空的深渊中漂浮着无数断裂的命运之线。',
    background: 'space_time_abyss',
    difficulty: 3,
    enemyIds: ['abyss_time_fish_001', 'deep_thread_entity_002'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 210, gold: 420, memoryShards: 21 }
  },
  {
    id: 'ch8_stage_019',
    name: '命运引导',
    chapter: 8,
    stageNumber: 19,
    description: '神秘的力量在引导着你，向命运的核心前进。',
    background: 'fate_guidance',
    difficulty: 3,
    enemyIds: ['guiding_thread_001', 'destiny_angler_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 215, gold: 430, memoryShards: 21 }
  },
  {
    id: 'ch8_stage_020',
    name: '初级命运兽',
    chapter: 8,
    stageNumber: 20,
    description: '一只由命运丝线编织而成的巨兽从虚空中苏醒。',
    background: 'junior_fate_beast_arena',
    difficulty: 3,
    enemyIds: ['fate_thread_beast_001'],
    enemyLevel: 4,
    isBossLevel: true,
    rewards: { exp: 320, gold: 750, memoryShards: 58 }
  },
  // ========== 中级区域 (第21-30关) 难度3-4 ==========
  {
    id: 'ch8_stage_021',
    name: '命运心脏',
    chapter: 8,
    stageNumber: 21,
    description: '到达命运的核心地带，无数丝线在此汇聚。',
    background: 'fate_heart',
    difficulty: 3,
    enemyIds: ['heart_fate_sentinel_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 240, gold: 480, memoryShards: 25 }
  },
  {
    id: 'ch8_stage_022',
    name: '命运墓地',
    chapter: 8,
    stageNumber: 22,
    description: '无数被遗忘的命运在此终结，形成了一片诡异的墓地。',
    background: 'fate_graveyard',
    difficulty: 3,
    enemyIds: ['fate_wraith_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 245, gold: 490, memoryShards: 25 }
  },
  {
    id: 'ch8_stage_023',
    name: '破碎命运',
    chapter: 8,
    stageNumber: 23,
    description: '命运之线在这里断裂，形成了危险的裂缝。',
    background: 'shattered_fate',
    difficulty: 4,
    enemyIds: ['broken_fate_apparition_001', 'thread_golem_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 255, gold: 510, memoryShards: 27 }
  },
  {
    id: 'ch8_stage_024',
    name: '命运风暴',
    chapter: 8,
    stageNumber: 24,
    description: '命运之力形成的风暴正在肆虐，丝线四处飞舞。',
    background: 'fate_storm_center',
    difficulty: 4,
    enemyIds: ['storm_fate_beast_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 260, gold: 520, memoryShards: 27 }
  },
  {
    id: 'ch8_stage_025',
    name: '命运编织者',
    chapter: 8,
    stageNumber: 25,
    description: '一位神秘的存在正在编织命运，创造新的可能性。',
    background: 'fate_weaver_lair',
    difficulty: 4,
    enemyIds: ['fate_weaver_master_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 265, gold: 530, memoryShards: 28 }
  },
  {
    id: 'ch8_stage_026',
    name: '命运遗迹',
    chapter: 8,
    stageNumber: 26,
    description: '古老的命运遗迹散落在时空之中，记录着失落的因果。',
    background: 'fate_ruins',
    difficulty: 4,
    enemyIds: ['ruin_fate_guardian_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 270, gold: 540, memoryShards: 28 }
  },
  {
    id: 'ch8_stage_027',
    name: '命运陷阱',
    chapter: 8,
    stageNumber: 27,
    description: '命运设下的陷阱层层叠叠，等待着猎物的到来。',
    background: 'fate_trap_zone',
    difficulty: 4,
    enemyIds: ['trap_thread_jellyfish_001', 'fate_hunter_001', 'destiny_angler_002'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 275, gold: 550, memoryShards: 29 }
  },
  {
    id: 'ch8_stage_028',
    name: '命运女王',
    chapter: 8,
    stageNumber: 28,
    description: '命运领域的女王显现，她掌控着无数生命的轨迹。',
    background: 'fate_queen_chamber',
    difficulty: 4,
    enemyIds: ['fate_queen_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 280, gold: 560, memoryShards: 29 }
  },
  {
    id: 'ch8_stage_029',
    name: '命运觉醒',
    chapter: 8,
    stageNumber: 29,
    description: '命运本身开始觉醒，它在观察着你的每一个选择。',
    background: 'awakened_fate',
    difficulty: 4,
    enemyIds: ['fate_eye_001', 'deep_thread_entity_003'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 285, gold: 570, memoryShards: 30 }
  },
  {
    id: 'ch8_stage_030',
    name: '中级命运兽',
    chapter: 8,
    stageNumber: 30,
    description: '一只巨大的命运吞噬者从时空中浮现，它的身体由因果构成。',
    background: 'mid_fate_beast_arena',
    difficulty: 4,
    enemyIds: ['fate_devourer_001'],
    enemyLevel: 5,
    isBossLevel: true,
    rewards: { exp: 440, gold: 1080, memoryShards: 86 }
  },
  // ========== 高级区域 (第31-40关) 难度4-5 ==========
  {
    id: 'ch8_stage_031',
    name: '命运深渊',
    chapter: 8,
    stageNumber: 31,
    description: '深入最黑暗的命运深渊，这里居住着最可怕的命运生物。',
    background: 'fate_abyss_deep',
    difficulty: 4,
    enemyIds: ['abyss_fate_horror_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 300, gold: 600, memoryShards: 35 }
  },
  {
    id: 'ch8_stage_032',
    name: '破碎因果',
    chapter: 8,
    stageNumber: 32,
    description: '因果关系在这里破碎，不同的现实交织在一起。',
    background: 'shattered_karma',
    difficulty: 4,
    enemyIds: ['karma_guardian_001', 'reality_thief_fate_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 305, gold: 610, memoryShards: 35 }
  },
  {
    id: 'ch8_stage_033',
    name: '愤怒命运',
    chapter: 8,
    stageNumber: 33,
    description: '命运对你的干预感到愤怒，它开始狂暴地收束丝线。',
    background: 'angry_fate',
    difficulty: 5,
    enemyIds: ['wrathful_fate_titan_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 320, gold: 640, memoryShards: 37 }
  },
  {
    id: 'ch8_stage_034',
    name: '命运囚牢',
    chapter: 8,
    stageNumber: 34,
    description: '被囚禁的命运灵魂在此，它们渴望自由却成为威胁。',
    background: 'fate_prison',
    difficulty: 5,
    enemyIds: ['imprisoned_destiny_001', 'fate_jailer_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 325, gold: 650, memoryShards: 37 }
  },
  {
    id: 'ch8_stage_035',
    name: '无限轮回',
    chapter: 8,
    stageNumber: 35,
    description: '轮回似乎没有尽头，无论怎么走都在原地打转。',
    background: 'infinite_reincarnation',
    difficulty: 5,
    enemyIds: ['loop_cycle_phantom_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 330, gold: 660, memoryShards: 38 }
  },
  {
    id: 'ch8_stage_036',
    name: '古老命运',
    chapter: 8,
    stageNumber: 36,
    description: '这里封印着最古老的命运，连时间都无法改变。',
    background: 'ancient_fate',
    difficulty: 5,
    enemyIds: ['ancient_fate_being_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 335, gold: 670, memoryShards: 38 }
  },
  {
    id: 'ch8_stage_037',
    name: '命运意志',
    chapter: 8,
    stageNumber: 37,
    description: '命运凝聚出了自己的意志，它要驱逐你这个干预者。',
    background: 'will_of_fate',
    difficulty: 5,
    enemyIds: ['fate_will_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 340, gold: 680, memoryShards: 39 }
  },
  {
    id: 'ch8_stage_038',
    name: '命运漩涡',
    chapter: 8,
    stageNumber: 38,
    description: '一个巨大的命运漩涡正在形成，吞噬着周围的一切因果。',
    background: 'fate_vortex',
    difficulty: 5,
    enemyIds: ['vortex_fate_guardian_001', 'sucked_destiny_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 345, gold: 690, memoryShards: 39 }
  },
  {
    id: 'ch8_stage_039',
    name: '最后的命运',
    chapter: 8,
    stageNumber: 39,
    description: '进入精英区域前的最后考验，你将面对命运最深的秘密。',
    background: 'final_fate_chamber',
    difficulty: 5,
    enemyIds: ['fate_sentinel_001', 'deep_fate_guardian_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 350, gold: 700, memoryShards: 40 }
  },
  {
    id: 'ch8_stage_040',
    name: '高级命运兽',
    chapter: 8,
    stageNumber: 40,
    description: '一只巨大的命运古龙从时空深处升起，它掌控着因果轮回。',
    background: 'high_fate_beast_arena',
    difficulty: 5,
    enemyIds: ['fate_dragon_001'],
    enemyLevel: 6,
    isBossLevel: true,
    rewards: { exp: 540, gold: 1340, memoryShards: 122 }
  },
  // ========== 精英区域 (第41-49关) 难度5 ==========
  {
    id: 'ch8_stage_041',
    name: '命运核心',
    chapter: 8,
    stageNumber: 41,
    description: '精英区域的起始，命运的最深处，因果达到极致。',
    background: 'fate_core',
    difficulty: 5,
    enemyIds: ['core_fate_defender_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 390, gold: 780, memoryShards: 42 }
  },
  {
    id: 'ch8_stage_042',
    name: '命运王座',
    chapter: 8,
    stageNumber: 42,
    description: '一座由命运丝线构成的王座，散发着宿命般的力量。',
    background: 'fate_throne',
    difficulty: 5,
    enemyIds: ['throne_destiny_usurper_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 395, gold: 790, memoryShards: 42 }
  },
  {
    id: 'ch8_stage_043',
    name: '无尽因果',
    chapter: 8,
    stageNumber: 43,
    description: '因果似乎没有边界，延伸到无限的命运之中。',
    background: 'endless_karma_zone',
    difficulty: 5,
    enemyIds: ['infinite_karma_entity_001', 'fate_lord_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 400, gold: 800, memoryShards: 43 }
  },
  {
    id: 'ch8_stage_044',
    name: '命运之源',
    chapter: 8,
    stageNumber: 44,
    description: '所有命运的源头，一个古老而强大的存在守护着这里。',
    background: 'source_of_fate',
    difficulty: 5,
    enemyIds: ['fate_source_guardian_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 405, gold: 810, memoryShards: 43 }
  },
  {
    id: 'ch8_stage_045',
    name: '命运大司命',
    chapter: 8,
    stageNumber: 45,
    description: '这片命运领域的最高司命，掌控着因果轮回的规则。',
    background: 'fate_archon_chamber',
    difficulty: 5,
    enemyIds: ['fate_archon_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 410, gold: 820, memoryShards: 44 }
  },
  {
    id: 'ch8_stage_046',
    name: '禁忌命运',
    chapter: 8,
    stageNumber: 46,
    description: '被封印的禁忌命运之力，任何进入者都将面对最可怕的宿命。',
    background: 'forbidden_fate',
    difficulty: 5,
    enemyIds: ['forbidden_fate_keeper_001', 'cursed_destiny_001'],
    enemyLevel: 7,
    isBossLevel: false,
    rewards: { exp: 415, gold: 830, memoryShards: 44 }
  },
  {
    id: 'ch8_stage_047',
    name: '命运的真相',
    chapter: 8,
    stageNumber: 47,
    description: '开始接近命运的真相，守卫变得更加神秘而强大。',
    background: 'truth_of_fate_chamber',
    difficulty: 5,
    enemyIds: ['fate_truth_guardian_001'],
    enemyLevel: 7,
    isBossLevel: false,
    rewards: { exp: 420, gold: 840, memoryShards: 45 }
  },
  {
    id: 'ch8_stage_048',
    name: '命运巅峰',
    chapter: 8,
    stageNumber: 48,
    description: '普通命运的巅峰，在这里你将面对最强大的命运生物。',
    background: 'peak_of_fate',
    difficulty: 5,
    enemyIds: ['peak_fate_being_001'],
    enemyLevel: 7,
    isBossLevel: false,
    rewards: { exp: 425, gold: 850, memoryShards: 45 }
  },
  {
    id: 'ch8_stage_049',
    name: '终极命运守卫',
    chapter: 8,
    stageNumber: 49,
    description: '精英区域的最终守卫，击败它才能面对章节Boss。',
    background: 'ultimate_fate_gate',
    difficulty: 5,
    enemyIds: ['ultimate_fate_sentinel_001', 'ultimate_destiny_defender_001'],
    enemyLevel: 7,
    isBossLevel: false,
    rewards: { exp: 430, gold: 860, memoryShards: 46 }
  },
  // ========== 章节Boss (第50关) 难度6 ==========
  {
    id: 'ch8_stage_050',
    name: '命运之主',
    chapter: 8,
    stageNumber: 50,
    description: '命运交织的真正主宰，她是因果轮回的化身，掌控着所有生命的命运之线。她能剪断命运之线，改变因果法则。只有战胜她，才能真正掌握自己的命运。',
    background: 'fate_master_throne',
    difficulty: 6,
    enemyIds: ['fate_overlord_001'],
    enemyLevel: 8,
    isBossLevel: true,
    rewards: { exp: 950, gold: 2600, memoryShards: 240 }
  }
];

export default Chapter8Stages;
