import { LevelConfig } from './LevelTypes';

/**
 * 第5章：时光回廊 (Chapter 5: Corridor of Time)
 * 主题：时间的回廊，过去与未来的交汇，时钟与沙漏
 * 风格：时光流转，钟表元素，过去与未来的交错
 */

export const Chapter5Stages: LevelConfig[] = [
  // ========== 教学/入门区域 (第1-10关) 难度1-2 ==========
  {
    id: 'ch5_stage_001',
    name: '时光入口',
    chapter: 5,
    stageNumber: 1,
    description: '你踏入时光回廊的入口，周围的景象开始变得模糊。',
    background: 'time_entrance',
    difficulty: 1,
    enemyIds: ['clock_sprite_001'],
    enemyLevel: 1,
    isBossLevel: false,
    rewards: { exp: 70, gold: 140, memoryShards: 9 }
  },
  {
    id: 'ch5_stage_002',
    name: '滴答回廊',
    chapter: 5,
    stageNumber: 2,
    description: '滴答声在回廊中回荡，那是时间流逝的声音。',
    background: 'ticking_corridor',
    difficulty: 1,
    enemyIds: ['clock_sprite_001', 'clock_sprite_002'],
    enemyLevel: 1,
    isBossLevel: false,
    rewards: { exp: 75, gold: 150, memoryShards: 9 }
  },
  {
    id: 'ch5_stage_003',
    name: '沙漏之室',
    chapter: 5,
    stageNumber: 3,
    description: '巨大的沙漏矗立在房间中央，沙子缓缓流下。',
    background: 'hourglass_chamber',
    difficulty: 1,
    enemyIds: ['sand_wisp_001'],
    enemyLevel: 1,
    isBossLevel: false,
    rewards: { exp: 80, gold: 160, memoryShards: 10 }
  },
  {
    id: 'ch5_stage_004',
    name: '过去的残影',
    chapter: 5,
    stageNumber: 4,
    description: '过去的残影在周围闪现，那是已经消逝的时光。',
    background: 'past_shadows',
    difficulty: 1,
    enemyIds: ['past_echo_001', 'clock_sprite_001'],
    enemyLevel: 1,
    isBossLevel: false,
    rewards: { exp: 85, gold: 170, memoryShards: 10 }
  },
  {
    id: 'ch5_stage_005',
    name: '时钟齿轮',
    chapter: 5,
    stageNumber: 5,
    description: '巨大的齿轮在空中转动，维持着时间的运转。',
    background: 'clock_gears',
    difficulty: 2,
    enemyIds: ['gear_spirit_001'],
    enemyLevel: 2,
    isBossLevel: false,
    rewards: { exp: 95, gold: 190, memoryShards: 11 }
  },
  {
    id: 'ch5_stage_006',
    name: '时光流逝',
    chapter: 5,
    stageNumber: 6,
    description: '时间在这里流逝得更快，你必须快速前进。',
    background: 'flowing_time',
    difficulty: 2,
    enemyIds: ['time_flow_spirit_001'],
    enemyLevel: 2,
    isBossLevel: false,
    rewards: { exp: 100, gold: 200, memoryShards: 11 }
  },
  {
    id: 'ch5_stage_007',
    name: '分秒之间',
    chapter: 5,
    stageNumber: 7,
    description: '分针与秒针交错，创造出时间的迷宫。',
    background: 'minute_maze',
    difficulty: 2,
    enemyIds: ['minute_hand_ghost_001', 'sand_wisp_001'],
    enemyLevel: 2,
    isBossLevel: false,
    rewards: { exp: 105, gold: 210, memoryShards: 12 }
  },
  {
    id: 'ch5_stage_008',
    name: '时光倒影',
    chapter: 5,
    stageNumber: 8,
    description: '时光在水面上倒映，展现出不同的过去。',
    background: 'time_reflection',
    difficulty: 2,
    enemyIds: ['reflection_wraith_001'],
    enemyLevel: 2,
    isBossLevel: false,
    rewards: { exp: 110, gold: 220, memoryShards: 12 }
  },
  {
    id: 'ch5_stage_009',
    name: '时之碎片',
    chapter: 5,
    stageNumber: 9,
    description: '时间的碎片漂浮在空中，每一片都包含着一段记忆。',
    background: 'time_fragments',
    difficulty: 2,
    enemyIds: ['fragment_time_001', 'time_flow_spirit_001'],
    enemyLevel: 2,
    isBossLevel: false,
    rewards: { exp: 115, gold: 230, memoryShards: 13 }
  },
  {
    id: 'ch5_stage_010',
    name: '时光守卫',
    chapter: 5,
    stageNumber: 10,
    description: '由时间能量构成的守卫挡住了去路，它掌控着时间的流动。',
    background: 'time_guardian_gate',
    difficulty: 2,
    enemyIds: ['time_guardian_001'],
    enemyLevel: 3,
    isBossLevel: true,
    rewards: { exp: 160, gold: 380, memoryShards: 24 }
  },
  // ========== 初级区域 (第11-20关) 难度2-3 ==========
  {
    id: 'ch5_stage_011',
    name: '深入回廊',
    chapter: 5,
    stageNumber: 11,
    description: '时光回廊变得更加复杂，时间的流动开始不稳定。',
    background: 'deep_time_corridor',
    difficulty: 2,
    enemyIds: ['time_crawler_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 140, gold: 280, memoryShards: 14 }
  },
  {
    id: 'ch5_stage_012',
    name: '时之裂痕',
    chapter: 5,
    stageNumber: 12,
    description: '时间的裂痕出现在空中，从中可以看到不同的时代。',
    background: 'time_crack',
    difficulty: 2,
    enemyIds: ['crack_entity_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 145, gold: 290, memoryShards: 14 }
  },
  {
    id: 'ch5_stage_013',
    name: '昨日之页',
    chapter: 5,
    stageNumber: 13,
    description: '一页页记录着昨日的书页在空中翻动，散发着古老的气息。',
    background: 'yesterday_pages',
    difficulty: 2,
    enemyIds: ['yesterday_keeper_001', 'clock_sprite_003'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 150, gold: 300, memoryShards: 15 }
  },
  {
    id: 'ch5_stage_014',
    name: '消逝的时光',
    chapter: 5,
    stageNumber: 14,
    description: '时光正在快速消逝，你必须在它消失前通过。',
    background: 'fading_time',
    difficulty: 3,
    enemyIds: ['fading_time_wraith_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 160, gold: 320, memoryShards: 16 }
  },
  {
    id: 'ch5_stage_015',
    name: '钟摆墓地',
    chapter: 5,
    stageNumber: 15,
    description: '废弃的钟摆堆积如山，它们曾经记录着无数时光。',
    background: 'pendulum_graveyard',
    difficulty: 3,
    enemyIds: ['pendulum_ghost_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 165, gold: 330, memoryShards: 16 }
  },
  {
    id: 'ch5_stage_016',
    name: '褪色的时钟',
    chapter: 5,
    stageNumber: 16,
    description: '古老的时钟已经褪色，但它们仍在默默记录时间。',
    background: 'faded_clocks',
    difficulty: 3,
    enemyIds: ['faded_clock_spirit_001', 'old_timekeeper_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 170, gold: 340, memoryShards: 17 }
  },
  {
    id: 'ch5_stage_017',
    name: '时光河流',
    chapter: 5,
    stageNumber: 17,
    description: '一条由时光组成的河流静静流淌，河水闪烁着光芒。',
    background: 'river_of_time',
    difficulty: 3,
    enemyIds: ['river_time_spirit_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 175, gold: 350, memoryShards: 17 }
  },
  {
    id: 'ch5_stage_018',
    name: '时间岔路',
    chapter: 5,
    stageNumber: 18,
    description: '多条时间线在前方展开，每一条都通向不同的未来。',
    background: 'time_crossroads',
    difficulty: 3,
    enemyIds: ['path_time_guardian_001', 'sand_wisp_002'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 180, gold: 360, memoryShards: 18 }
  },
  {
    id: 'ch5_stage_019',
    name: '未来碎片',
    chapter: 5,
    stageNumber: 19,
    description: '未来的碎片在回廊中漂浮，展示着可能的命运。',
    background: 'future_fragments_field',
    difficulty: 3,
    enemyIds: ['future_collector_001', 'past_echo_002'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 185, gold: 370, memoryShards: 18 }
  },
  {
    id: 'ch5_stage_020',
    name: '初级时光者',
    chapter: 5,
    stageNumber: 20,
    description: '一个掌握初级时光之力的存在出现，它要守护这片回廊。',
    background: 'junior_timekeeper_arena',
    difficulty: 3,
    enemyIds: ['junior_timekeeper_001'],
    enemyLevel: 4,
    isBossLevel: true,
    rewards: { exp: 260, gold: 600, memoryShards: 45 }
  },
  // ========== 中级区域 (第21-30关) 难度3-4 ==========
  {
    id: 'ch5_stage_021',
    name: '时光心脏',
    chapter: 5,
    stageNumber: 21,
    description: '到达时光回廊的心脏地带，时间的力量最为浓郁。',
    background: 'time_heart',
    difficulty: 3,
    enemyIds: ['heart_time_sentinel_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 200, gold: 400, memoryShards: 20 }
  },
  {
    id: 'ch5_stage_022',
    name: '时间墓地',
    chapter: 5,
    stageNumber: 22,
    description: '被遗忘的时间在这里沉睡，但有些不愿安息。',
    background: 'time_graveyard',
    difficulty: 3,
    enemyIds: ['time_ghost_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 205, gold: 410, memoryShards: 20 }
  },
  {
    id: 'ch5_stage_023',
    name: '时光画廊',
    chapter: 5,
    stageNumber: 23,
    description: '画廊中展示着不同时代的画面，画中时间正在流逝。',
    background: 'time_gallery',
    difficulty: 4,
    enemyIds: ['gallery_time_apparition_001', 'painting_time_ghost_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 215, gold: 430, memoryShards: 22 }
  },
  {
    id: 'ch5_stage_024',
    name: '永恒喷泉',
    chapter: 5,
    stageNumber: 24,
    description: '一座喷涌着永恒时光的喷泉，时间在这里变得缓慢。',
    background: 'fountain_of_eternity',
    difficulty: 4,
    enemyIds: ['eternity_guardian_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 220, gold: 440, memoryShards: 22 }
  },
  {
    id: 'ch5_stage_025',
    name: '时光编织者',
    chapter: 5,
    stageNumber: 25,
    description: '一个神秘的存在正在编织时间线，创造新的可能性。',
    background: 'time_weaver_chamber',
    difficulty: 4,
    enemyIds: ['time_weaver_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 225, gold: 450, memoryShards: 23 }
  },
  {
    id: 'ch5_stage_026',
    name: '无名时代',
    chapter: 5,
    stageNumber: 26,
    description: '一个被遗忘的时代，连它的名字都已消失在时间中。',
    background: 'nameless_era',
    difficulty: 4,
    enemyIds: ['era_apparition_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 230, gold: 460, memoryShards: 23 }
  },
  {
    id: 'ch5_stage_027',
    name: '时间陷阱',
    chapter: 5,
    stageNumber: 27,
    description: '时光回廊布满了陷阱，让你的时间不断流失。',
    background: 'time_trap_zone',
    difficulty: 4,
    enemyIds: ['time_trap_spirit_001', 'time_trap_spirit_002', 'clock_sprite_004'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 235, gold: 470, memoryShards: 24 }
  },
  {
    id: 'ch5_stage_028',
    name: '过去的灰烬',
    chapter: 5,
    stageNumber: 28,
    description: '曾经辉煌的时代，如今只剩下灰烬和回忆。',
    background: 'ashes_of_past_era',
    difficulty: 4,
    enemyIds: ['ash_time_memory_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 240, gold: 480, memoryShards: 24 }
  },
  {
    id: 'ch5_stage_029',
    name: '时光的觉醒',
    chapter: 5,
    stageNumber: 29,
    description: '时光本身开始觉醒，它意识到了你的存在。',
    background: 'awakened_time',
    difficulty: 4,
    enemyIds: ['time_eye_001', 'time_crawler_002'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 245, gold: 490, memoryShards: 25 }
  },
  {
    id: 'ch5_stage_030',
    name: '中级时光者',
    chapter: 5,
    stageNumber: 30,
    description: '中级区域的时光之主降临，它掌握着更深层的时光之力。',
    background: 'mid_timekeeper_arena',
    difficulty: 4,
    enemyIds: ['mid_timekeeper_001'],
    enemyLevel: 5,
    isBossLevel: true,
    rewards: { exp: 370, gold: 880, memoryShards: 66 }
  },
  // ========== 高级区域 (第31-40关) 难度4-5 ==========
  {
    id: 'ch5_stage_031',
    name: '深渊时光',
    chapter: 5,
    stageNumber: 31,
    description: '深入最神秘的时间深渊，这里的时间法则与众不同。',
    background: 'abyssal_time',
    difficulty: 4,
    enemyIds: ['abyss_time_horror_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 260, gold: 520, memoryShards: 28 }
  },
  {
    id: 'ch5_stage_032',
    name: '破碎的时间',
    chapter: 5,
    stageNumber: 32,
    description: '你的时间线开始出现裂痕，过去与未来变得混乱。',
    background: 'fractured_time',
    difficulty: 4,
    enemyIds: ['time_fragment_ghost_001', 'timeline_thief_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 265, gold: 530, memoryShards: 28 }
  },
  {
    id: 'ch5_stage_033',
    name: '愤怒的时钟',
    chapter: 5,
    stageNumber: 33,
    description: '被遗忘的时间充满了愤怒，它们不愿被忽视。',
    background: 'angry_clock',
    difficulty: 5,
    enemyIds: ['angry_time_forgotten_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 280, gold: 560, memoryShards: 30 }
  },
  {
    id: 'ch5_stage_034',
    name: '时间的囚牢',
    chapter: 5,
    stageNumber: 34,
    description: '某些时间被囚禁在此，它们被遗忘却又不被释放。',
    background: 'time_prison',
    difficulty: 5,
    enemyIds: ['imprisoned_time_001', 'time_prison_warden_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 285, gold: 570, memoryShards: 30 }
  },
  {
    id: 'ch5_stage_035',
    name: '无限时光',
    chapter: 5,
    stageNumber: 35,
    description: '时间似乎没有尽头，无论怎么走都在重复同一天。',
    background: 'infinite_time_loop',
    difficulty: 5,
    enemyIds: ['time_loop_phantom_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 290, gold: 580, memoryShards: 31 }
  },
  {
    id: 'ch5_stage_036',
    name: '古老的时光',
    chapter: 5,
    stageNumber: 36,
    description: '这里封印着最古老的时光，连现在都无法触及。',
    background: 'ancient_time',
    difficulty: 5,
    enemyIds: ['ancient_time_being_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 295, gold: 590, memoryShards: 31 }
  },
  {
    id: 'ch5_stage_037',
    name: '时间的意志',
    chapter: 5,
    stageNumber: 37,
    description: '时间凝聚出了自己的意志，它在抵抗你的前进。',
    background: 'will_of_time',
    difficulty: 5,
    enemyIds: ['time_will_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 300, gold: 600, memoryShards: 32 }
  },
  {
    id: 'ch5_stage_038',
    name: '时光漩涡',
    chapter: 5,
    stageNumber: 38,
    description: '一个由流失时间组成的漩涡，吞噬着一切进入其中的东西。',
    background: 'time_vortex',
    difficulty: 5,
    enemyIds: ['vortex_guardian_time_001', 'sucked_time_ghost_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 305, gold: 610, memoryShards: 32 }
  },
  {
    id: 'ch5_stage_039',
    name: '最后的时光',
    chapter: 5,
    stageNumber: 39,
    description: '进入精英区域前的最终时光，你必须抵抗深层的时间。',
    background: 'final_time_chamber',
    difficulty: 5,
    enemyIds: ['final_time_sentinel_001', 'final_time_guardian_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 310, gold: 620, memoryShards: 33 }
  },
  {
    id: 'ch5_stage_040',
    name: '高级时光者',
    chapter: 5,
    stageNumber: 40,
    description: '高级区域的时光之主现身，它的力量足以操控任何时间。',
    background: 'high_timekeeper_arena',
    difficulty: 5,
    enemyIds: ['high_timekeeper_001'],
    enemyLevel: 6,
    isBossLevel: true,
    rewards: { exp: 460, gold: 1100, memoryShards: 94 }
  },
  // ========== 精英区域 (第41-49关) 难度5 ==========
  {
    id: 'ch5_stage_041',
    name: '时光核心',
    chapter: 5,
    stageNumber: 41,
    description: '精英区域的起始，时光的核心地带，时间最为浓郁。',
    background: 'time_core',
    difficulty: 5,
    enemyIds: ['core_time_defender_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 340, gold: 680, memoryShards: 34 }
  },
  {
    id: 'ch5_stage_042',
    name: '永恒王座',
    chapter: 5,
    stageNumber: 42,
    description: '一座由永恒时光构成的王座，散发着无尽的时间之力。',
    background: 'eternity_throne',
    difficulty: 5,
    enemyIds: ['throne_usurper_time_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 345, gold: 690, memoryShards: 34 }
  },
  {
    id: 'ch5_stage_043',
    name: '无尽时光',
    chapter: 5,
    stageNumber: 43,
    description: '时光似乎没有边界，延伸到无限的过去与未来。',
    background: 'endless_time_zone',
    difficulty: 5,
    enemyIds: ['infinite_time_entity_001', 'time_lord_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 350, gold: 700, memoryShards: 35 }
  },
  {
    id: 'ch5_stage_044',
    name: '时光之源',
    chapter: 5,
    stageNumber: 44,
    description: '所有时光的源头，一个古老而强大的存在守护着这里。',
    background: 'source_of_time',
    difficulty: 5,
    enemyIds: ['time_source_guardian_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 355, gold: 710, memoryShards: 35 }
  },
  {
    id: 'ch5_stage_045',
    name: '时光典狱长',
    chapter: 5,
    stageNumber: 45,
    description: '这片时光回廊的典狱长，掌控着时间与历史的规则。',
    background: 'time_warden_chamber',
    difficulty: 5,
    enemyIds: ['time_warden_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 360, gold: 720, memoryShards: 36 }
  },
  {
    id: 'ch5_stage_046',
    name: '禁忌时光',
    chapter: 5,
    stageNumber: 46,
    description: '禁忌的时光被封印在此，任何触碰都可能改变历史。',
    background: 'forbidden_time',
    difficulty: 5,
    enemyIds: ['forbidden_time_keeper_001', 'cursed_clock_001'],
    enemyLevel: 7,
    isBossLevel: false,
    rewards: { exp: 365, gold: 730, memoryShards: 36 }
  },
  {
    id: 'ch5_stage_047',
    name: '时光的真相',
    chapter: 5,
    stageNumber: 47,
    description: '开始接近时光回廊的真相，守卫变得更加疯狂。',
    background: 'truth_of_time_chamber',
    difficulty: 5,
    enemyIds: ['time_truth_guardian_001'],
    enemyLevel: 7,
    isBossLevel: false,
    rewards: { exp: 370, gold: 740, memoryShards: 37 }
  },
  {
    id: 'ch5_stage_048',
    name: '时光巅峰',
    chapter: 5,
    stageNumber: 48,
    description: '普通时光的巅峰，在这里你将面对最强大的时间体。',
    background: 'peak_of_time',
    difficulty: 5,
    enemyIds: ['peak_time_being_001'],
    enemyLevel: 7,
    isBossLevel: false,
    rewards: { exp: 375, gold: 750, memoryShards: 37 }
  },
  {
    id: 'ch5_stage_049',
    name: '终极时光守卫',
    chapter: 5,
    stageNumber: 49,
    description: '精英区域的最终守卫，击败它才能面对章节Boss。',
    background: 'ultimate_time_gate',
    difficulty: 5,
    enemyIds: ['ultimate_time_sentinel_001', 'ultimate_time_defender_001'],
    enemyLevel: 7,
    isBossLevel: false,
    rewards: { exp: 380, gold: 760, memoryShards: 38 }
  },
  // ========== 章节Boss (第50关) 难度6 ==========
  {
    id: 'ch5_stage_050',
    name: '时光之主',
    chapter: 5,
    stageNumber: 50,
    description: '时光回廊的真正主宰，它是时间的化身，掌控着过去、现在与未来。它能操控时间的流速，让敌人衰老或逆转伤害。只有战胜它，才能掌握时间的奥秘。',
    background: 'lord_of_time_throne',
    difficulty: 6,
    enemyIds: ['chronos_overlord_001'],
    enemyLevel: 8,
    isBossLevel: true,
    rewards: { exp: 750, gold: 2000, memoryShards: 180 }
  }
];

export default Chapter5Stages;
