import { LevelConfig } from './LevelTypes';

/**
 * 第1章：记忆迷宫 (Chapter 1: Memory Labyrinth)
 * 主题：神秘的迷宫，代表着人类记忆的复杂性
 * 风格：柔和的灯光，书卷气息，古老图书馆
 */

export const Chapter1Stages: LevelConfig[] = [
  // ========== 教学/入门区域 (第1-10关) 难度1-2 ==========
  {
    id: 'ch1_stage_001',
    name: '初入迷宫',
    chapter: 1,
    stageNumber: 1,
    description: '你踏入记忆迷宫的第一步，这里是最初的记忆碎片散落之地。',
    background: 'library_entrance',
    difficulty: 1,
    enemyIds: ['shadow_minion_001'],
    enemyLevel: 1,
    isBossLevel: false,
    rewards: { exp: 50, gold: 100, memoryShards: 5 }
  },
  {
    id: 'ch1_stage_002',
    name: '微光指引',
    chapter: 1,
    stageNumber: 2,
    description: '微弱的记忆之光在前方闪烁，指引着迷失的灵魂。',
    background: 'dim_corridor',
    difficulty: 1,
    enemyIds: ['shadow_minion_001', 'shadow_minion_002'],
    enemyLevel: 1,
    isBossLevel: false,
    rewards: { exp: 55, gold: 110, memoryShards: 6 }
  },
  {
    id: 'ch1_stage_003',
    name: '书架之间',
    chapter: 1,
    stageNumber: 3,
    description: '古老的书架排列成迷宫，每本书都储存着一段记忆。',
    background: 'bookshelf_maze',
    difficulty: 1,
    enemyIds: ['paper_wisp_001'],
    enemyLevel: 1,
    isBossLevel: false,
    rewards: { exp: 60, gold: 120, memoryShards: 6 }
  },
  {
    id: 'ch1_stage_004',
    name: '遗忘角落',
    chapter: 1,
    stageNumber: 4,
    description: '被遗忘的角落藏着不愿回忆的往事。',
    background: 'dusty_corner',
    difficulty: 1,
    enemyIds: ['shadow_minion_002', 'paper_wisp_001'],
    enemyLevel: 1,
    isBossLevel: false,
    rewards: { exp: 65, gold: 130, memoryShards: 7 }
  },
  {
    id: 'ch1_stage_005',
    name: '墨香浮动',
    chapter: 1,
    stageNumber: 5,
    description: '古老的墨水气味弥漫，文字开始有了生命。',
    background: 'ink_pool',
    difficulty: 2,
    enemyIds: ['ink_spirit_001'],
    enemyLevel: 2,
    isBossLevel: false,
    rewards: { exp: 75, gold: 150, memoryShards: 8 }
  },
  {
    id: 'ch1_stage_006',
    name: '回声长廊',
    chapter: 1,
    stageNumber: 6,
    description: '走廊中回荡着过去的声音，有些记忆不愿被触碰。',
    background: 'echo_hallway',
    difficulty: 2,
    enemyIds: ['echo_ghost_001'],
    enemyLevel: 2,
    isBossLevel: false,
    rewards: { exp: 80, gold: 160, memoryShards: 8 }
  },
  {
    id: 'ch1_stage_007',
    name: '碎片之室',
    chapter: 1,
    stageNumber: 7,
    description: '破碎的记忆镜片悬浮在空中，反射出不同的过去。',
    background: 'mirror_chamber',
    difficulty: 2,
    enemyIds: ['mirror_shard_001', 'shadow_minion_001'],
    enemyLevel: 2,
    isBossLevel: false,
    rewards: { exp: 85, gold: 170, memoryShards: 9 }
  },
  {
    id: 'ch1_stage_008',
    name: '记忆低语',
    chapter: 1,
    stageNumber: 8,
    description: '低语声越来越清晰，这些记忆想要被听到。',
    background: 'whisper_room',
    difficulty: 2,
    enemyIds: ['whisper_spirit_001'],
    enemyLevel: 2,
    isBossLevel: false,
    rewards: { exp: 90, gold: 180, memoryShards: 9 }
  },
  {
    id: 'ch1_stage_009',
    name: '时光残页',
    chapter: 1,
    stageNumber: 9,
    description: '漂浮的纸张记录着消逝的时光，守护着它们的灵体苏醒了。',
    background: 'floating_pages',
    difficulty: 2,
    enemyIds: ['paper_wisp_002', 'ink_spirit_001'],
    enemyLevel: 2,
    isBossLevel: false,
    rewards: { exp: 95, gold: 190, memoryShards: 10 }
  },
  {
    id: 'ch1_stage_010',
    name: '迷宫守门人',
    chapter: 1,
    stageNumber: 10,
    description: '入门区域的守护者挡住了去路，击败它才能继续前进。',
    background: 'guardian_gate',
    difficulty: 2,
    enemyIds: ['gate_guardian_001'],
    enemyLevel: 3,
    isBossLevel: true,
    rewards: { exp: 120, gold: 250, memoryShards: 15 }
  },
  // ========== 初级区域 (第11-20关) 难度2-3 ==========
  {
    id: 'ch1_stage_011',
    name: '深入迷宫',
    chapter: 1,
    stageNumber: 11,
    description: '迷宫的路径变得复杂，记忆的力量也在增强。',
    background: 'twisted_path',
    difficulty: 2,
    enemyIds: ['shadow_stalker_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 100, gold: 200, memoryShards: 10 }
  },
  {
    id: 'ch1_stage_012',
    name: '镜中倒影',
    chapter: 1,
    stageNumber: 12,
    description: '镜子中的另一个自己似乎在说着什么秘密。',
    background: 'mirror_maze',
    difficulty: 2,
    enemyIds: ['mirror_self_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 105, gold: 210, memoryShards: 11 }
  },
  {
    id: 'ch1_stage_013',
    name: '文字陷阱',
    chapter: 1,
    stageNumber: 13,
    description: '某些文字变成了陷阱，要小心它们的攻击。',
    background: 'trapped_library',
    difficulty: 2,
    enemyIds: ['rune_trap_001', 'ink_spirit_002'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 110, gold: 220, memoryShards: 11 }
  },
  {
    id: 'ch1_stage_014',
    name: '迷失的回声',
    chapter: 1,
    stageNumber: 14,
    description: '回声变得更加强烈，它们在试图混淆你的方向感。',
    background: 'deep_echo_chamber',
    difficulty: 3,
    enemyIds: ['echo_wraith_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 120, gold: 240, memoryShards: 12 }
  },
  {
    id: 'ch1_stage_015',
    name: '墨水深渊',
    chapter: 1,
    stageNumber: 15,
    description: '墨水池似乎在呼唤着什么，深不见底。',
    background: 'ink_abyss',
    difficulty: 3,
    enemyIds: ['ink_leviathan_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 125, gold: 250, memoryShards: 12 }
  },
  {
    id: 'ch1_stage_016',
    name: '破碎的往事',
    chapter: 1,
    stageNumber: 16,
    description: '一些记忆碎片开始组合，形成新的威胁。',
    background: 'shattered_memory',
    difficulty: 3,
    enemyIds: ['memory_construct_001', 'shadow_stalker_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 130, gold: 260, memoryShards: 13 }
  },
  {
    id: 'ch1_stage_017',
    name: '低语的源头',
    chapter: 1,
    stageNumber: 17,
    description: '追踪低语的源头，发现了一个被囚禁的记忆体。',
    background: 'whisper_source',
    difficulty: 3,
    enemyIds: ['trapped_memory_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 135, gold: 270, memoryShards: 13 }
  },
  {
    id: 'ch1_stage_018',
    name: '迷宫岔路',
    chapter: 1,
    stageNumber: 18,
    description: '多条道路在眼前展开，选择决定着命运。',
    background: 'crossroads',
    difficulty: 3,
    enemyIds: ['path_guardian_001', 'path_guardian_002'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 140, gold: 280, memoryShards: 14 }
  },
  {
    id: 'ch1_stage_019',
    name: '幻影迷宫',
    chapter: 1,
    stageNumber: 19,
    description: '迷宫开始移动，墙壁变得不再可靠。',
    background: 'shifting_maze',
    difficulty: 3,
    enemyIds: ['maze_phantom_001', 'shadow_stalker_002'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 145, gold: 290, memoryShards: 14 }
  },
  {
    id: 'ch1_stage_020',
    name: '初级守护者',
    chapter: 1,
    stageNumber: 20,
    description: '初级区域的守护者出现，只有战胜它才能进入更深的迷宫。',
    background: 'junior_guardian_arena',
    difficulty: 3,
    enemyIds: ['junior_guardian_001'],
    enemyLevel: 4,
    isBossLevel: true,
    rewards: { exp: 180, gold: 400, memoryShards: 25 }
  },
  // ========== 中级区域 (第21-30关) 难度3-4 ==========
  {
    id: 'ch1_stage_021',
    name: '迷宫心脏',
    chapter: 1,
    stageNumber: 21,
    description: '到达迷宫的中心地带，记忆的能量更加浓郁。',
    background: 'maze_heart',
    difficulty: 3,
    enemyIds: ['heart_sentinel_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 150, gold: 300, memoryShards: 15 }
  },
  {
    id: 'ch1_stage_022',
    name: '记忆的重量',
    chapter: 1,
    stageNumber: 22,
    description: '某些记忆承载着太多情感，它们变得异常沉重。',
    background: 'heavy_memory_hall',
    difficulty: 3,
    enemyIds: ['burden_wraith_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 155, gold: 310, memoryShards: 15 }
  },
  {
    id: 'ch1_stage_023',
    name: '双面镜面',
    chapter: 1,
    stageNumber: 23,
    description: '镜子不再只是反射，它们开始创造新的现实。',
    background: 'double_mirror_room',
    difficulty: 4,
    enemyIds: ['mirror_twin_001', 'mirror_twin_002'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 165, gold: 330, memoryShards: 16 }
  },
  {
    id: 'ch1_stage_024',
    name: '墨水洪流',
    chapter: 1,
    stageNumber: 24,
    description: '墨水如洪水般涌来，携带着古老的知识和危险。',
    background: 'ink_flood',
    difficulty: 4,
    enemyIds: ['ink_flood_beast_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 170, gold: 340, memoryShards: 16 }
  },
  {
    id: 'ch1_stage_025',
    name: '回声之主',
    chapter: 1,
    stageNumber: 25,
    description: '所有的回声汇聚在一起，形成了一个强大的实体。',
    background: 'echo_throne',
    difficulty: 4,
    enemyIds: ['echo_lord_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 175, gold: 350, memoryShards: 17 }
  },
  {
    id: 'ch1_stage_026',
    name: '记忆编织者',
    chapter: 1,
    stageNumber: 26,
    description: '一个神秘的存在正在编织新的记忆，它的目的是什么？',
    background: 'weaver_chamber',
    difficulty: 4,
    enemyIds: ['memory_weaver_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 180, gold: 360, memoryShards: 17 }
  },
  {
    id: 'ch1_stage_027',
    name: '迷宫陷阱',
    chapter: 1,
    stageNumber: 27,
    description: '迷宫本身似乎想要阻止你前进，处处都是陷阱。',
    background: 'trapped_corridor',
    difficulty: 4,
    enemyIds: ['maze_trap_001', 'maze_trap_002', 'maze_trap_003'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 185, gold: 370, memoryShards: 18 }
  },
  {
    id: 'ch1_stage_028',
    name: '知识的代价',
    chapter: 1,
    stageNumber: 28,
    description: '获取知识需要付出代价，这里的守护者不会免费给予。',
    background: 'knowledge_altar',
    difficulty: 4,
    enemyIds: ['knowledge_keeper_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 190, gold: 380, memoryShards: 18 }
  },
  {
    id: 'ch1_stage_029',
    name: '迷宫的觉醒',
    chapter: 1,
    stageNumber: 29,
    description: '迷宫似乎有了意识，它在观察着你的每一个动作。',
    background: 'awakened_maze',
    difficulty: 4,
    enemyIds: ['maze_eye_001', 'shadow_horror_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 195, gold: 390, memoryShards: 19 }
  },
  {
    id: 'ch1_stage_030',
    name: '中级守护者',
    chapter: 1,
    stageNumber: 30,
    description: '中级区域的守护者降临，它掌握着更强大的记忆之力。',
    background: 'mid_guardian_arena',
    difficulty: 4,
    enemyIds: ['mid_guardian_001'],
    enemyLevel: 5,
    isBossLevel: true,
    rewards: { exp: 250, gold: 550, memoryShards: 35 }
  },
  // ========== 高级区域 (第31-40关) 难度4-5 ==========
  {
    id: 'ch1_stage_031',
    name: '迷宫深渊',
    chapter: 1,
    stageNumber: 31,
    description: '深入迷宫最黑暗的区域，这里的记忆充满了恐惧。',
    background: 'maze_abyss',
    difficulty: 4,
    enemyIds: ['abyss_horror_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 200, gold: 400, memoryShards: 20 }
  },
  {
    id: 'ch1_stage_032',
    name: '破碎的自我',
    chapter: 1,
    stageNumber: 32,
    description: '镜子中分裂出无数个自己，每一个都代表着不同的记忆。',
    background: 'fractured_self',
    difficulty: 4,
    enemyIds: ['self_fragment_001', 'self_fragment_002', 'self_fragment_003'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 205, gold: 410, memoryShards: 20 }
  },
  {
    id: 'ch1_stage_033',
    name: '墨水的愤怒',
    chapter: 1,
    stageNumber: 33,
    description: '墨水沸腾了，它们对你的入侵感到愤怒。',
    background: 'angry_ink_pool',
    difficulty: 5,
    enemyIds: ['angry_ink_titan_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 220, gold: 440, memoryShards: 22 }
  },
  {
    id: 'ch1_stage_034',
    name: '记忆的牢笼',
    chapter: 1,
    stageNumber: 34,
    description: '某些记忆被囚禁了太久，它们渴望自由，却成为了威胁。',
    background: 'memory_prison',
    difficulty: 5,
    enemyIds: ['imprisoned_memory_001', 'prison_warden_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 225, gold: 450, memoryShards: 22 }
  },
  {
    id: 'ch1_stage_035',
    name: '无限回廊',
    chapter: 1,
    stageNumber: 35,
    description: '一条似乎永无止境的走廊，重复着相同的场景。',
    background: 'infinite_hallway',
    difficulty: 5,
    enemyIds: ['loop_phantom_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 230, gold: 460, memoryShards: 23 }
  },
  {
    id: 'ch1_stage_036',
    name: '古老文献',
    chapter: 1,
    stageNumber: 36,
    description: '禁书区的古老文献开始翻动，释放出被封印的存在。',
    background: 'forbidden_archives',
    difficulty: 5,
    enemyIds: ['ancient_tome_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 235, gold: 470, memoryShards: 23 }
  },
  {
    id: 'ch1_stage_037',
    name: '迷宫意志',
    chapter: 1,
    stageNumber: 37,
    description: '迷宫本身凝聚出了一个意志，它要驱逐所有入侵者。',
    background: 'maze_consciousness',
    difficulty: 5,
    enemyIds: ['maze_will_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 240, gold: 480, memoryShards: 24 }
  },
  {
    id: 'ch1_stage_038',
    name: '记忆的漩涡',
    chapter: 1,
    stageNumber: 38,
    description: '强大的记忆漩涡形成，试图将你吞噬。',
    background: 'memory_vortex',
    difficulty: 5,
    enemyIds: ['vortex_guardian_001', 'sucked_memory_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 245, gold: 490, memoryShards: 24 }
  },
  {
    id: 'ch1_stage_039',
    name: '最后的考验',
    chapter: 1,
    stageNumber: 39,
    description: '进入精英区域前的最后考验，准备迎接真正的挑战。',
    background: 'final_test_chamber',
    difficulty: 5,
    enemyIds: ['test_sentinel_001', 'test_sentinel_002'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 250, gold: 500, memoryShards: 25 }
  },
  {
    id: 'ch1_stage_040',
    name: '高级守护者',
    chapter: 1,
    stageNumber: 40,
    description: '高级区域的守护者现身，它拥有操控迷宫的能力。',
    background: 'high_guardian_arena',
    difficulty: 5,
    enemyIds: ['high_guardian_001'],
    enemyLevel: 6,
    isBossLevel: true,
    rewards: { exp: 320, gold: 700, memoryShards: 50 }
  },
  // ========== 精英区域 (第41-49关) 难度5 ==========
  {
    id: 'ch1_stage_041',
    name: '迷宫核心',
    chapter: 1,
    stageNumber: 41,
    description: '精英区域的起始，迷宫的核心地带，能量极其浓郁。',
    background: 'maze_core',
    difficulty: 5,
    enemyIds: ['core_defender_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 260, gold: 520, memoryShards: 26 }
  },
  {
    id: 'ch1_stage_042',
    name: '记忆之王座',
    chapter: 1,
    stageNumber: 42,
    description: '一座由记忆碎片构成的王座，坐在上面的存在不可小觑。',
    background: 'memory_throne',
    difficulty: 5,
    enemyIds: ['throne_usurper_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 265, gold: 530, memoryShards: 26 }
  },
  {
    id: 'ch1_stage_043',
    name: '无尽的镜面',
    chapter: 1,
    stageNumber: 43,
    description: '无数个镜子组成的房间，每一个都通往不同的可能性。',
    background: 'endless_mirror_room',
    difficulty: 5,
    enemyIds: ['infinite_reflection_001', 'mirror_lord_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 270, gold: 540, memoryShards: 27 }
  },
  {
    id: 'ch1_stage_044',
    name: '墨水的源头',
    chapter: 1,
    stageNumber: 44,
    description: '所有墨水的源头，一个古老而强大的存在守护着这里。',
    background: 'ink_source',
    difficulty: 5,
    enemyIds: ['ink_source_guardian_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 275, gold: 550, memoryShards: 27 }
  },
  {
    id: 'ch1_stage_045',
    name: '迷宫的图书馆长',
    chapter: 1,
    stageNumber: 45,
    description: '迷宫图书馆的守护者，掌握着无尽的知识和力量。',
    background: 'librarian_chamber',
    difficulty: 5,
    enemyIds: ['maze_librarian_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 280, gold: 560, memoryShards: 28 }
  },
  {
    id: 'ch1_stage_046',
    name: '禁忌知识',
    chapter: 1,
    stageNumber: 46,
    description: '禁忌的知识在召唤，但它们被重重守护。',
    background: 'forbidden_knowledge_altar',
    difficulty: 5,
    enemyIds: ['forbidden_keeper_001', 'cursed_tome_001'],
    enemyLevel: 7,
    isBossLevel: false,
    rewards: { exp: 285, gold: 570, memoryShards: 28 }
  },
  {
    id: 'ch1_stage_047',
    name: '迷宫的真相',
    chapter: 1,
    stageNumber: 47,
    description: '开始接近迷宫的真相，守卫也变得更加疯狂。',
    background: 'maze_truth_chamber',
    difficulty: 5,
    enemyIds: ['truth_guardian_001'],
    enemyLevel: 7,
    isBossLevel: false,
    rewards: { exp: 290, gold: 580, memoryShards: 29 }
  },
  {
    id: 'ch1_stage_048',
    name: '记忆的巅峰',
    chapter: 1,
    stageNumber: 48,
    description: '普通记忆的巅峰，在这里你将面对最强大的记忆体。',
    background: 'memory_peak',
    difficulty: 5,
    enemyIds: ['peak_memory_being_001'],
    enemyLevel: 7,
    isBossLevel: false,
    rewards: { exp: 295, gold: 590, memoryShards: 29 }
  },
  {
    id: 'ch1_stage_049',
    name: '终极守护者',
    chapter: 1,
    stageNumber: 49,
    description: '精英区域的最终守卫，击败它就能面对章节Boss。',
    background: 'ultimate_guardian_gate',
    difficulty: 5,
    enemyIds: ['ultimate_sentinel_001', 'ultimate_defender_001'],
    enemyLevel: 7,
    isBossLevel: false,
    rewards: { exp: 300, gold: 600, memoryShards: 30 }
  },
  // ========== 章节Boss (第50关) 难度6 ==========
  {
    id: 'ch1_stage_050',
    name: '迷宫之主',
    chapter: 1,
    stageNumber: 50,
    description: '记忆迷宫的真正主宰，掌控着所有记忆和路径。只有战胜它，才能真正理解这个迷宫的秘密。',
    background: 'labyrinth_master_throne',
    difficulty: 6,
    enemyIds: ['labyrinth_master_001'],
    enemyLevel: 8,
    isBossLevel: true,
    rewards: { exp: 500, gold: 1200, memoryShards: 100 }
  }
];

export default Chapter1Stages;
