import { LevelConfig } from './LevelTypes';

/**
 * 第3章：深海回忆 (Chapter 3: Deep Sea Memories)
 * 主题：深海中的记忆，水下世界，沉船与海底遗迹
 * 风格：幽蓝深海，波光粼粼，神秘莫测
 */

export const Chapter3Stages: LevelConfig[] = [
  // ========== 教学/入门区域 (第1-10关) 难度1-2 ==========
  {
    id: 'ch3_stage_001',
    name: '浅海初探',
    chapter: 3,
    stageNumber: 1,
    description: '温暖的浅海区域，阳光还能穿透水面，这里是进入深海的第一步。',
    background: 'shallow_sea',
    difficulty: 1,
    enemyIds: ['water_sprite_001'],
    enemyLevel: 1,
    isBossLevel: false,
    rewards: { exp: 60, gold: 120, memoryShards: 7 }
  },
  {
    id: 'ch3_stage_002',
    name: '波光粼粼',
    chapter: 3,
    stageNumber: 2,
    description: '阳光在水面下折射出美丽的光芒，但水下暗藏着危险。',
    background: 'shimmering_waters',
    difficulty: 1,
    enemyIds: ['water_sprite_001', 'water_sprite_002'],
    enemyLevel: 1,
    isBossLevel: false,
    rewards: { exp: 65, gold: 130, memoryShards: 7 }
  },
  {
    id: 'ch3_stage_003',
    name: '珊瑚礁林',
    chapter: 3,
    stageNumber: 3,
    description: '五颜六色的珊瑚礁形成了一座水下森林，迷失其中容易陷入困境。',
    background: 'coral_reef_forest',
    difficulty: 1,
    enemyIds: ['coral_guardian_001'],
    enemyLevel: 1,
    isBossLevel: false,
    rewards: { exp: 70, gold: 140, memoryShards: 8 }
  },
  {
    id: 'ch3_stage_004',
    name: '潮汐洞穴',
    chapter: 3,
    stageNumber: 4,
    description: '海水潮汐形成的洞穴，里面藏着古老的秘密。',
    background: 'tide_cave',
    difficulty: 1,
    enemyIds: ['tide_spirit_001', 'water_sprite_001'],
    enemyLevel: 1,
    isBossLevel: false,
    rewards: { exp: 75, gold: 150, memoryShards: 8 }
  },
  {
    id: 'ch3_stage_005',
    name: '水母之舞',
    chapter: 3,
    stageNumber: 5,
    description: '发光的水母在水中翩翩起舞，它们的触须带有微弱的电流。',
    background: 'jellyfish_dance',
    difficulty: 2,
    enemyIds: ['glowing_jellyfish_001'],
    enemyLevel: 2,
    isBossLevel: false,
    rewards: { exp: 85, gold: 170, memoryShards: 9 }
  },
  {
    id: 'ch3_stage_006',
    name: '深海呼吸',
    chapter: 3,
    stageNumber: 6,
    description: '水压开始增大，你需要适应深海的环境才能继续前进。',
    background: 'deep_sea_breathing',
    difficulty: 2,
    enemyIds: ['pressure_spirit_001'],
    enemyLevel: 2,
    isBossLevel: false,
    rewards: { exp: 90, gold: 180, memoryShards: 9 }
  },
  {
    id: 'ch3_stage_007',
    name: '海藻缠绕',
    chapter: 3,
    stageNumber: 7,
    description: '巨大的海藻像森林一样茂密，小心不要被它们缠住。',
    background: 'kelp_forest',
    difficulty: 2,
    enemyIds: ['kelp_entangler_001', 'water_sprite_002'],
    enemyLevel: 2,
    isBossLevel: false,
    rewards: { exp: 95, gold: 190, memoryShards: 10 }
  },
  {
    id: 'ch3_stage_008',
    name: '沉船残骸',
    chapter: 3,
    stageNumber: 8,
    description: '一艘古老的沉船静静躺在海底，里面似乎还有生命的迹象。',
    background: 'shipwreck',
    difficulty: 2,
    enemyIds: ['shipwreck_ghost_001'],
    enemyLevel: 2,
    isBossLevel: false,
    rewards: { exp: 100, gold: 200, memoryShards: 10 }
  },
  {
    id: 'ch3_stage_009',
    name: '鱼群风暴',
    chapter: 3,
    stageNumber: 9,
    description: '成群的鱼类形成了一场水下风暴，它们守护着这片海域。',
    background: 'fish_storm',
    difficulty: 2,
    enemyIds: ['fish_swarm_001', 'fish_guardian_001'],
    enemyLevel: 2,
    isBossLevel: false,
    rewards: { exp: 105, gold: 210, memoryShards: 11 }
  },
  {
    id: 'ch3_stage_010',
    name: '海域守卫',
    chapter: 3,
    stageNumber: 10,
    description: '一只巨大的海龟挡住了去路，它是这片海域的守护者。',
    background: 'sea_guardian_gate',
    difficulty: 2,
    enemyIds: ['giant_sea_turtle_001'],
    enemyLevel: 3,
    isBossLevel: true,
    rewards: { exp: 140, gold: 310, memoryShards: 20 }
  },
  // ========== 初级区域 (第11-20关) 难度2-3 ==========
  {
    id: 'ch3_stage_011',
    name: '深海下潜',
    chapter: 3,
    stageNumber: 11,
    description: '开始向更深的海域下潜，阳光逐渐消失。',
    background: 'deep_dive',
    difficulty: 2,
    enemyIds: ['deep_water_entity_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 120, gold: 240, memoryShards: 12 }
  },
  {
    id: 'ch3_stage_012',
    name: '海底峡谷',
    chapter: 3,
    stageNumber: 12,
    description: '一道深邃的海底峡谷横亘在前方，深处传来神秘的声音。',
    background: 'undersea_canyon',
    difficulty: 2,
    enemyIds: ['canyon_dweller_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 125, gold: 250, memoryShards: 12 }
  },
  {
    id: 'ch3_stage_013',
    name: '珍珠洞穴',
    chapter: 3,
    stageNumber: 13,
    description: '洞穴中布满了巨大的珍珠，但守护它们的生物并不友好。',
    background: 'pearl_cave',
    difficulty: 2,
    enemyIds: ['pearl_guardian_001', 'water_sprite_003'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 130, gold: 260, memoryShards: 13 }
  },
  {
    id: 'ch3_stage_014',
    name: '深海暗流',
    chapter: 3,
    stageNumber: 14,
    description: '看不见的暗流在水下涌动，稍有不慎就会被卷走。',
    background: 'deep_current',
    difficulty: 3,
    enemyIds: ['current_wraith_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 140, gold: 280, memoryShards: 14 }
  },
  {
    id: 'ch3_stage_015',
    name: '古老锚链',
    chapter: 3,
    stageNumber: 15,
    description: '巨大的锚链从上方垂下，连接着某艘沉没的巨舰。',
    background: 'ancient_anchor',
    difficulty: 3,
    enemyIds: ['anchor_spirit_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 145, gold: 290, memoryShards: 14 }
  },
  {
    id: 'ch3_stage_016',
    name: '水手亡魂',
    chapter: 3,
    stageNumber: 16,
    description: '沉没船只的水手们化为亡魂，在这片海域徘徊不去。',
    background: 'sailor_graveyard',
    difficulty: 3,
    enemyIds: ['sailor_ghost_001', 'drowned_sailor_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 150, gold: 300, memoryShards: 15 }
  },
  {
    id: 'ch3_stage_017',
    name: '海底温泉',
    chapter: 3,
    stageNumber: 17,
    description: '海底的热泉喷涌而出，形成了独特的生态系统。',
    background: 'undersea_vent',
    difficulty: 3,
    enemyIds: ['vent_creature_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 155, gold: 310, memoryShards: 15 }
  },
  {
    id: 'ch3_stage_018',
    name: '黑暗深渊',
    chapter: 3,
    stageNumber: 18,
    description: '阳光已经彻底消失，前方是一片漆黑的海底深渊。',
    background: 'dark_abyss',
    difficulty: 3,
    enemyIds: ['abyss_fish_001', 'deep_water_entity_002'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 160, gold: 320, memoryShards: 16 }
  },
  {
    id: 'ch3_stage_019',
    name: '发光鱼群',
    chapter: 3,
    stageNumber: 19,
    description: '一群发光的鱼类照亮了黑暗的海底，它们似乎在引导着什么。',
    background: 'glowing_fish_swarm',
    difficulty: 3,
    enemyIds: ['light_fish_001', 'angler_fish_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 165, gold: 330, memoryShards: 16 }
  },
  {
    id: 'ch3_stage_020',
    name: '初级海怪',
    chapter: 3,
    stageNumber: 20,
    description: '一只巨大的章鱼从沉船中苏醒，它的触手遍布整片海域。',
    background: 'giant_octopus_arena',
    difficulty: 3,
    enemyIds: ['giant_octopus_001'],
    enemyLevel: 4,
    isBossLevel: true,
    rewards: { exp: 220, gold: 500, memoryShards: 35 }
  },
  // ========== 中级区域 (第21-30关) 难度3-4 ==========
  {
    id: 'ch3_stage_021',
    name: '深海之心',
    chapter: 3,
    stageNumber: 21,
    description: '到达深海的核心地带，水压达到极限，但生命依然顽强。',
    background: 'deep_sea_heart',
    difficulty: 3,
    enemyIds: ['deep_heart_sentinel_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 180, gold: 360, memoryShards: 18 }
  },
  {
    id: 'ch3_stage_022',
    name: '海底墓地',
    chapter: 3,
    stageNumber: 22,
    description: '无数沉船在这里堆积，形成了一片船体的墓地。',
    background: 'ship_graveyard',
    difficulty: 3,
    enemyIds: ['shipwreck_wraith_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 185, gold: 370, memoryShards: 18 }
  },
  {
    id: 'ch3_stage_023',
    name: '沉没宫殿',
    chapter: 3,
    stageNumber: 23,
    description: '一座宏伟的宫殿沉睡在海底，曾经辉煌的文明已经消逝。',
    background: 'sunken_palace',
    difficulty: 4,
    enemyIds: ['palace_apparition_001', 'coral_golem_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 195, gold: 390, memoryShards: 20 }
  },
  {
    id: 'ch3_stage_024',
    name: '深海火山',
    chapter: 3,
    stageNumber: 24,
    description: '海底的火山正在喷发，岩浆与海水交融产生奇异的景象。',
    background: 'undersea_volcano',
    difficulty: 4,
    enemyIds: ['magma_sea_creature_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 200, gold: 400, memoryShards: 20 }
  },
  {
    id: 'ch3_stage_025',
    name: '深渊编织者',
    chapter: 3,
    stageNumber: 25,
    description: '一个神秘的存在在深海中编织着记忆之网，捕捉迷失的灵魂。',
    background: 'abyss_weaver_lair',
    difficulty: 4,
    enemyIds: ['abyss_weaver_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 205, gold: 410, memoryShards: 21 }
  },
  {
    id: 'ch3_stage_026',
    name: '海底遗迹',
    chapter: 3,
    stageNumber: 26,
    description: '古老的遗迹散落在海底，记录着失落的文明。',
    background: 'undersea_ruins',
    difficulty: 4,
    enemyIds: ['ruin_guardian_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 210, gold: 420, memoryShards: 21 }
  },
  {
    id: 'ch3_stage_027',
    name: '深海陷阱',
    chapter: 3,
    stageNumber: 27,
    description: '深海捕食者设下了层层陷阱，等待着猎物的到来。',
    background: 'deep_sea_trap',
    difficulty: 4,
    enemyIds: ['trap_jellyfish_001', 'hunter_fish_001', 'angler_fish_002'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 215, gold: 430, memoryShards: 22 }
  },
  {
    id: 'ch3_stage_028',
    name: '珍珠女王',
    chapter: 3,
    stageNumber: 28,
    description: '珍珠洞穴的女王苏醒，她不会轻易让出她的宝藏。',
    background: 'pearl_queen_chamber',
    difficulty: 4,
    enemyIds: ['pearl_queen_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 220, gold: 440, memoryShards: 22 }
  },
  {
    id: 'ch3_stage_029',
    name: '深海的觉醒',
    chapter: 3,
    stageNumber: 29,
    description: '深海似乎有了意识，它开始注意到你这个外来者。',
    background: 'awakened_deep_sea',
    difficulty: 4,
    enemyIds: ['sea_eye_001', 'deep_water_entity_003'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 225, gold: 450, memoryShards: 23 }
  },
  {
    id: 'ch3_stage_030',
    name: '中级海怪',
    chapter: 3,
    stageNumber: 30,
    description: '一只巨大的鲨鱼从深渊中浮现，它的眼睛闪烁着智慧的光芒。',
    background: 'mid_sea_monster_arena',
    difficulty: 4,
    enemyIds: ['giant_shark_king_001'],
    enemyLevel: 5,
    isBossLevel: true,
    rewards: { exp: 310, gold: 700, memoryShards: 50 }
  },
  // ========== 高级区域 (第31-40关) 难度4-5 ==========
  {
    id: 'ch3_stage_031',
    name: '海底深渊',
    chapter: 3,
    stageNumber: 31,
    description: '深入最黑暗的海底深渊，这里居住着最可怕的生物。',
    background: 'abyssal_depths',
    difficulty: 4,
    enemyIds: ['abyss_horror_002'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 240, gold: 480, memoryShards: 24 }
  },
  {
    id: 'ch3_stage_032',
    name: '破碎的海图',
    chapter: 3,
    stageNumber: 32,
    description: '破碎的海图漂浮在水中，指引着通往宝藏的道路，但也有危险。',
    background: 'shattered_sea_chart',
    difficulty: 4,
    enemyIds: ['chart_guardian_001', 'treasure_thief_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 245, gold: 490, memoryShards: 24 }
  },
  {
    id: 'ch3_stage_033',
    name: '愤怒的深海',
    chapter: 3,
    stageNumber: 33,
    description: '深海对你的入侵感到愤怒，海水变得狂暴不安。',
    background: 'angry_sea',
    difficulty: 5,
    enemyIds: ['angry_sea_titan_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 260, gold: 520, memoryShards: 26 }
  },
  {
    id: 'ch3_stage_034',
    name: '水手的囚牢',
    chapter: 3,
    stageNumber: 34,
    description: '被困的水手灵魂被囚禁在此，它们渴望解脱却成为威胁。',
    background: 'sailor_prison',
    difficulty: 5,
    enemyIds: ['imprisoned_sailor_001', 'sea_warden_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 265, gold: 530, memoryShards: 26 }
  },
  {
    id: 'ch3_stage_035',
    name: '无限海沟',
    chapter: 3,
    stageNumber: 35,
    description: '一道似乎没有尽头的海沟，深渊的凝视从下方传来。',
    background: 'infinite_trench',
    difficulty: 5,
    enemyIds: ['trench_phantom_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 270, gold: 540, memoryShards: 27 }
  },
  {
    id: 'ch3_stage_036',
    name: '古老沉船',
    chapter: 3,
    stageNumber: 36,
    description: '一艘来自远古时代的沉船，里面封印着不可名状的存在。',
    background: 'ancient_shipwreck',
    difficulty: 5,
    enemyIds: ['ancient_sea_being_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 275, gold: 550, memoryShards: 27 }
  },
  {
    id: 'ch3_stage_037',
    name: '海洋意志',
    chapter: 3,
    stageNumber: 37,
    description: '海洋本身凝聚出了意志，它要驱逐你这个入侵者。',
    background: 'will_of_sea',
    difficulty: 5,
    enemyIds: ['sea_will_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 280, gold: 560, memoryShards: 28 }
  },
  {
    id: 'ch3_stage_038',
    name: '海底漩涡',
    chapter: 3,
    stageNumber: 38,
    description: '一个巨大的水下漩涡正在形成，吞噬着周围的一切。',
    background: 'undersea_vortex',
    difficulty: 5,
    enemyIds: ['vortex_guardian_003', 'sucked_ship_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 285, gold: 570, memoryShards: 28 }
  },
  {
    id: 'ch3_stage_039',
    name: '最后的潜水',
    chapter: 3,
    stageNumber: 39,
    description: '进入精英区域前的最后下潜，你将面对深海最深的秘密。',
    background: 'final_dive_chamber',
    difficulty: 5,
    enemyIds: ['dive_sentinel_001', 'deep_guardian_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 290, gold: 580, memoryShards: 29 }
  },
  {
    id: 'ch3_stage_040',
    name: '高级海怪',
    chapter: 3,
    stageNumber: 40,
    description: '一只巨大的鲸鱼从深海浮现，它是这片海域的真正霸主。',
    background: 'high_sea_monster_arena',
    difficulty: 5,
    enemyIds: ['leviathan_whale_001'],
    enemyLevel: 6,
    isBossLevel: true,
    rewards: { exp: 380, gold: 860, memoryShards: 70 }
  },
  // ========== 精英区域 (第41-49关) 难度5 ==========
  {
    id: 'ch3_stage_041',
    name: '深海核心',
    chapter: 3,
    stageNumber: 41,
    description: '精英区域的起始，深海的最深处，压力与黑暗达到极致。',
    background: 'deep_sea_core',
    difficulty: 5,
    enemyIds: ['core_sea_defender_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 300, gold: 600, memoryShards: 30 }
  },
  {
    id: 'ch3_stage_042',
    name: '沉没王座',
    chapter: 3,
    stageNumber: 42,
    description: '一座沉没的王座，曾经属于海洋的统治者。',
    background: 'sunken_throne',
    difficulty: 5,
    enemyIds: ['throne_usurper_sea_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 305, gold: 610, memoryShards: 30 }
  },
  {
    id: 'ch3_stage_043',
    name: '无尽深渊',
    chapter: 3,
    stageNumber: 43,
    description: '深渊似乎没有尽头，越是深入越是迷失。',
    background: 'endless_abyss',
    difficulty: 5,
    enemyIds: ['infinite_abyss_entity_001', 'deep_lord_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 310, gold: 620, memoryShards: 31 }
  },
  {
    id: 'ch3_stage_044',
    name: '深海之源',
    chapter: 3,
    stageNumber: 44,
    description: '所有深海的源头，一个古老而强大的存在守护着这里。',
    background: 'source_of_deep_sea',
    difficulty: 5,
    enemyIds: ['deep_source_guardian_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 315, gold: 630, memoryShards: 31 }
  },
  {
    id: 'ch3_stage_045',
    name: '海底典狱长',
    chapter: 3,
    stageNumber: 45,
    description: '这片深海区域的典狱长，掌控着海压与暗流的规则。',
    background: 'sea_warden_chamber',
    difficulty: 5,
    enemyIds: ['sea_warden_boss_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 320, gold: 640, memoryShards: 32 }
  },
  {
    id: 'ch3_stage_046',
    name: '禁忌海域',
    chapter: 3,
    stageNumber: 46,
    description: '禁忌的海域被封印在此，任何进入者都将面对最可怕的噩梦。',
    background: 'forbidden_sea',
    difficulty: 5,
    enemyIds: ['forbidden_sea_keeper_001', 'cursed_kraken_001'],
    enemyLevel: 7,
    isBossLevel: false,
    rewards: { exp: 325, gold: 650, memoryShards: 32 }
  },
  {
    id: 'ch3_stage_047',
    name: '深海的真相',
    chapter: 3,
    stageNumber: 47,
    description: '开始接近深海的真相，守卫变得更加疯狂而强大。',
    background: 'truth_of_sea_chamber',
    difficulty: 5,
    enemyIds: ['sea_truth_guardian_001'],
    enemyLevel: 7,
    isBossLevel: false,
    rewards: { exp: 330, gold: 660, memoryShards: 33 }
  },
  {
    id: 'ch3_stage_048',
    name: '深海巅峰',
    chapter: 3,
    stageNumber: 48,
    description: '普通深海的巅峰，在这里你将面对最强大的深海生物。',
    background: 'peak_of_deep_sea',
    difficulty: 5,
    enemyIds: ['peak_sea_being_001'],
    enemyLevel: 7,
    isBossLevel: false,
    rewards: { exp: 335, gold: 670, memoryShards: 33 }
  },
  {
    id: 'ch3_stage_049',
    name: '终极深海守卫',
    chapter: 3,
    stageNumber: 49,
    description: '精英区域的最终守卫，击败它才能面对章节Boss。',
    background: 'ultimate_sea_gate',
    difficulty: 5,
    enemyIds: ['ultimate_sea_sentinel_001', 'ultimate_deep_defender_001'],
    enemyLevel: 7,
    isBossLevel: false,
    rewards: { exp: 340, gold: 680, memoryShards: 34 }
  },
  // ========== 章节Boss (第50关) 难度6 ==========
  {
    id: 'ch3_stage_050',
    name: '深海之主',
    chapter: 3,
    stageNumber: 50,
    description: '深海回忆的真正主宰，它是海洋的化身，掌控着所有沉没的记忆与宝藏。它既是创造者也是毁灭者，只有战胜它，才能解开深海的秘密。',
    background: 'lord_of_deep_sea_throne',
    difficulty: 6,
    enemyIds: ['ocean_monarch_001'],
    enemyLevel: 8,
    isBossLevel: true,
    rewards: { exp: 600, gold: 1600, memoryShards: 140 }
  }
];

export default Chapter3Stages;
