import { LevelConfig } from './LevelTypes';

/**
 * 第6章：虚空边境 (Chapter 6: Void Frontier)
 * 主题：虚空的边缘，黑暗与虚无，空间裂缝
 * 风格：无尽黑暗，星光点点，空间扭曲
 */

export const Chapter6Stages: LevelConfig[] = [
  // ========== 教学/入门区域 (第1-10关) 难度1-2 ==========
  {
    id: 'ch6_stage_001',
    name: '虚空入口',
    chapter: 6,
    stageNumber: 1,
    description: '你来到虚空边境的入口，周围的现实开始扭曲。',
    background: 'void_entrance',
    difficulty: 1,
    enemyIds: ['void_wisp_001'],
    enemyLevel: 1,
    isBossLevel: false,
    rewards: { exp: 75, gold: 150, memoryShards: 10 }
  },
  {
    id: 'ch6_stage_002',
    name: '虚无小径',
    chapter: 6,
    stageNumber: 2,
    description: '虚无的小径延伸向黑暗深处，脚下没有实感。',
    background: 'nothingness_path',
    difficulty: 1,
    enemyIds: ['void_wisp_001', 'void_wisp_002'],
    enemyLevel: 1,
    isBossLevel: false,
    rewards: { exp: 80, gold: 160, memoryShards: 10 }
  },
  {
    id: 'ch6_stage_003',
    name: '黑暗之谷',
    chapter: 6,
    stageNumber: 3,
    description: '黑暗的山谷吞噬了所有光线，只有虚空生物发出微光。',
    background: 'darkness_valley',
    difficulty: 1,
    enemyIds: ['darkness_crawler_001'],
    enemyLevel: 1,
    isBossLevel: false,
    rewards: { exp: 85, gold: 170, memoryShards: 11 }
  },
  {
    id: 'ch6_stage_004',
    name: '星光点点',
    chapter: 6,
    stageNumber: 4,
    description: '虚空中偶尔闪烁的星光，那是遥远世界的倒影。',
    background: 'starlight_spots',
    difficulty: 1,
    enemyIds: ['star_fragment_001', 'void_wisp_001'],
    enemyLevel: 1,
    isBossLevel: false,
    rewards: { exp: 90, gold: 180, memoryShards: 11 }
  },
  {
    id: 'ch6_stage_005',
    name: '空间裂缝',
    chapter: 6,
    stageNumber: 5,
    description: '空间出现了细小的裂缝，从中透出不可名状的光芒。',
    background: 'space_crack',
    difficulty: 2,
    enemyIds: ['rift_spawn_001'],
    enemyLevel: 2,
    isBossLevel: false,
    rewards: { exp: 100, gold: 200, memoryShards: 12 }
  },
  {
    id: 'ch6_stage_006',
    name: '虚无呼吸',
    chapter: 6,
    stageNumber: 6,
    description: '空气中弥漫着虚无的气息，让你的存在变得模糊。',
    background: 'void_breath',
    difficulty: 2,
    enemyIds: ['void_mist_001'],
    enemyLevel: 2,
    isBossLevel: false,
    rewards: { exp: 105, gold: 210, memoryShards: 12 }
  },
  {
    id: 'ch6_stage_007',
    name: '暗影缠绕',
    chapter: 6,
    stageNumber: 7,
    description: '暗影像触手一样缠绕着空间，小心不要被它们困住。',
    background: 'shadow_tangle',
    difficulty: 2,
    enemyIds: ['shadow_tentacle_001', 'void_wisp_002'],
    enemyLevel: 2,
    isBossLevel: false,
    rewards: { exp: 110, gold: 220, memoryShards: 13 }
  },
  {
    id: 'ch6_stage_008',
    name: '虚空碎片',
    chapter: 6,
    stageNumber: 8,
    description: '虚空的碎片漂浮在周围，每一片都包含着虚无之力。',
    background: 'void_shards',
    difficulty: 2,
    enemyIds: ['shard_entity_001'],
    enemyLevel: 2,
    isBossLevel: false,
    rewards: { exp: 115, gold: 230, memoryShards: 13 }
  },
  {
    id: 'ch6_stage_009',
    name: '虚无风暴',
    chapter: 6,
    stageNumber: 9,
    description: '虚无的风暴席卷而来，试图吞噬一切存在。',
    background: 'void_storm',
    difficulty: 2,
    enemyIds: ['storm_void_spirit_001', 'void_mist_001'],
    enemyLevel: 2,
    isBossLevel: false,
    rewards: { exp: 120, gold: 240, memoryShards: 14 }
  },
  {
    id: 'ch6_stage_010',
    name: '虚空守卫',
    chapter: 6,
    stageNumber: 10,
    description: '由虚空能量构成的守卫挡住了去路，它散发着虚无的气息。',
    background: 'void_guardian_gate',
    difficulty: 2,
    enemyIds: ['void_guardian_001'],
    enemyLevel: 3,
    isBossLevel: true,
    rewards: { exp: 170, gold: 420, memoryShards: 26 }
  },
  // ========== 初级区域 (第11-20关) 难度2-3 ==========
  {
    id: 'ch6_stage_011',
    name: '深入虚空',
    chapter: 6,
    stageNumber: 11,
    description: '开始向虚空深处探索，现实的法则变得不稳定。',
    background: 'deep_void',
    difficulty: 2,
    enemyIds: ['deep_void_entity_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 150, gold: 300, memoryShards: 15 }
  },
  {
    id: 'ch6_stage_012',
    name: '空间峡谷',
    chapter: 6,
    stageNumber: 12,
    description: '一道由空间断裂形成的峡谷横亘在前方，深处传来呼啸声。',
    background: 'space_canyon',
    difficulty: 2,
    enemyIds: ['canyon_void_lurker_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 155, gold: 310, memoryShards: 15 }
  },
  {
    id: 'ch6_stage_013',
    name: '虚无洞穴',
    chapter: 6,
    stageNumber: 13,
    description: '洞穴内部充满了虚无能量，普通人进入就会消失。',
    background: 'void_cave',
    difficulty: 2,
    enemyIds: ['cave_void_guardian_001', 'void_wisp_003'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 160, gold: 320, memoryShards: 16 }
  },
  {
    id: 'ch6_stage_014',
    name: '暗流涌动',
    chapter: 6,
    stageNumber: 14,
    description: '看不见的虚空暗流在涌动，稍有不慎就会被卷入虚无。',
    background: 'void_current',
    difficulty: 3,
    enemyIds: ['current_void_wraith_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 170, gold: 340, memoryShards: 17 }
  },
  {
    id: 'ch6_stage_015',
    name: '古老裂缝',
    chapter: 6,
    stageNumber: 15,
    description: '巨大的古老裂缝从上方延伸，连接着某个未知的空间。',
    background: 'ancient_rift',
    difficulty: 3,
    enemyIds: ['rift_spirit_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 175, gold: 350, memoryShards: 17 }
  },
  {
    id: 'ch6_stage_016',
    name: '虚空亡魂',
    chapter: 6,
    stageNumber: 16,
    description: '迷失在虚空中的灵魂化为亡魂，在这片边境徘徊不去。',
    background: 'void_soul_graveyard',
    difficulty: 3,
    enemyIds: ['void_ghost_001', 'lost_void_soul_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 180, gold: 360, memoryShards: 18 }
  },
  {
    id: 'ch6_stage_017',
    name: '虚无之泉',
    chapter: 6,
    stageNumber: 17,
    description: '一个喷涌着虚无能量的泉眼，周围的空间都在扭曲。',
    background: 'void_spring',
    difficulty: 3,
    enemyIds: ['spring_void_creature_001'],
    enemyLevel: 3,
    isBossLevel: false,
    rewards: { exp: 185, gold: 370, memoryShards: 18 }
  },
  {
    id: 'ch6_stage_018',
    name: '黑暗深渊',
    chapter: 6,
    stageNumber: 18,
    description: '前方是一片纯粹的黑暗深渊，没有任何光线。',
    background: 'dark_abyss_void',
    difficulty: 3,
    enemyIds: ['abyss_void_fish_001', 'deep_void_entity_002'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 190, gold: 380, memoryShards: 19 }
  },
  {
    id: 'ch6_stage_019',
    name: '星光引导',
    chapter: 6,
    stageNumber: 19,
    description: '一群星光组成的生物照亮了黑暗的虚空，它们似乎在引导着什么。',
    background: 'starlight_guide',
    difficulty: 3,
    enemyIds: ['light_star_001', 'dark_angler_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 195, gold: 390, memoryShards: 19 }
  },
  {
    id: 'ch6_stage_020',
    name: '初级虚空兽',
    chapter: 6,
    stageNumber: 20,
    description: '一只巨大的虚空生物从黑暗中苏醒，它的身体由虚无构成。',
    background: 'junior_void_beast_arena',
    difficulty: 3,
    enemyIds: ['void_beast_junior_001'],
    enemyLevel: 4,
    isBossLevel: true,
    rewards: { exp: 280, gold: 650, memoryShards: 50 }
  },
  // ========== 中级区域 (第21-30关) 难度3-4 ==========
  {
    id: 'ch6_stage_021',
    name: '虚空心脏',
    chapter: 6,
    stageNumber: 21,
    description: '到达虚空的核心地带，虚无的能量最为浓郁。',
    background: 'void_heart',
    difficulty: 3,
    enemyIds: ['heart_void_sentinel_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 210, gold: 420, memoryShards: 21 }
  },
  {
    id: 'ch6_stage_022',
    name: '虚空墓地',
    chapter: 6,
    stageNumber: 22,
    description: '无数被虚空吞噬的世界遗迹，埋葬着无数文明。',
    background: 'void_graveyard',
    difficulty: 3,
    enemyIds: ['void_world_wraith_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 215, gold: 430, memoryShards: 21 }
  },
  {
    id: 'ch6_stage_023',
    name: '破碎宫殿',
    chapter: 6,
    stageNumber: 23,
    description: '一座在虚空中破碎的宫殿，曾经辉煌的文明已经消逝。',
    background: 'shattered_palace',
    difficulty: 4,
    enemyIds: ['palace_void_apparition_001', 'void_golem_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 225, gold: 450, memoryShards: 23 }
  },
  {
    id: 'ch6_stage_024',
    name: '虚空风暴',
    chapter: 6,
    stageNumber: 24,
    description: '虚空风暴正在肆虐，空间碎片四处飞舞。',
    background: 'void_storm_center',
    difficulty: 4,
    enemyIds: ['storm_void_beast_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 230, gold: 460, memoryShards: 23 }
  },
  {
    id: 'ch6_stage_025',
    name: '虚空编织者',
    chapter: 6,
    stageNumber: 25,
    description: '一个神秘的存在正在编织虚空，创造新的虚无生物。',
    background: 'void_weaver_lair',
    difficulty: 4,
    enemyIds: ['void_weaver_001'],
    enemyLevel: 4,
    isBossLevel: false,
    rewards: { exp: 235, gold: 470, memoryShards: 24 }
  },
  {
    id: 'ch6_stage_026',
    name: '虚空遗迹',
    chapter: 6,
    stageNumber: 26,
    description: '古老的虚空遗迹散落在边境，记录着失落的维度。',
    background: 'void_ruins',
    difficulty: 4,
    enemyIds: ['ruin_void_guardian_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 240, gold: 480, memoryShards: 24 }
  },
  {
    id: 'ch6_stage_027',
    name: '虚空陷阱',
    chapter: 6,
    stageNumber: 27,
    description: '虚空捕食者设下了层层陷阱，等待着猎物的到来。',
    background: 'void_trap_zone',
    difficulty: 4,
    enemyIds: ['trap_void_jellyfish_001', 'hunter_void_001', 'dark_angler_002'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 245, gold: 490, memoryShards: 25 }
  },
  {
    id: 'ch6_stage_028',
    name: '虚空女王',
    chapter: 6,
    stageNumber: 28,
    description: '虚空领域的女王苏醒，她不会轻易让出她的领地。',
    background: 'void_queen_chamber',
    difficulty: 4,
    enemyIds: ['void_queen_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 250, gold: 500, memoryShards: 25 }
  },
  {
    id: 'ch6_stage_029',
    name: '虚空的觉醒',
    chapter: 6,
    stageNumber: 29,
    description: '虚空本身开始觉醒，它开始注意到你这个外来者。',
    background: 'awakened_void',
    difficulty: 4,
    enemyIds: ['void_eye_001', 'deep_void_entity_003'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 255, gold: 510, memoryShards: 26 }
  },
  {
    id: 'ch6_stage_030',
    name: '中级虚空兽',
    chapter: 6,
    stageNumber: 30,
    description: '一只巨大的虚空吞噬者从深渊中浮现，它的身体如同黑洞。',
    background: 'mid_void_beast_arena',
    difficulty: 4,
    enemyIds: ['void_devourer_001'],
    enemyLevel: 5,
    isBossLevel: true,
    rewards: { exp: 400, gold: 960, memoryShards: 74 }
  },
  // ========== 高级区域 (第31-40关) 难度4-5 ==========
  {
    id: 'ch6_stage_031',
    name: '虚空深渊',
    chapter: 6,
    stageNumber: 31,
    description: '深入最黑暗的虚空深渊，这里居住着最可怕的虚空生物。',
    background: 'void_abyss_deep',
    difficulty: 4,
    enemyIds: ['abyss_void_horror_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 270, gold: 540, memoryShards: 30 }
  },
  {
    id: 'ch6_stage_032',
    name: '破碎的维度',
    chapter: 6,
    stageNumber: 32,
    description: '维度在这里破碎，不同的现实交织在一起。',
    background: 'shattered_dimension',
    difficulty: 4,
    enemyIds: ['dimension_guardian_001', 'reality_thief_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 275, gold: 550, memoryShards: 30 }
  },
  {
    id: 'ch6_stage_033',
    name: '愤怒的虚空',
    chapter: 6,
    stageNumber: 33,
    description: '虚空对你的入侵感到愤怒，它开始狂暴地吞噬一切。',
    background: 'angry_void',
    difficulty: 5,
    enemyIds: ['angry_void_titan_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 290, gold: 580, memoryShards: 32 }
  },
  {
    id: 'ch6_stage_034',
    name: '虚空囚牢',
    chapter: 6,
    stageNumber: 34,
    description: '被困的虚空灵魂被囚禁在此，它们渴望解脱却成为威胁。',
    background: 'void_prison',
    difficulty: 5,
    enemyIds: ['imprisoned_void_001', 'void_warden_001'],
    enemyLevel: 5,
    isBossLevel: false,
    rewards: { exp: 295, gold: 590, memoryShards: 32 }
  },
  {
    id: 'ch6_stage_035',
    name: '无限虚空',
    chapter: 6,
    stageNumber: 35,
    description: '虚空似乎没有尽头，无论怎么走都在原地打转。',
    background: 'infinite_void',
    difficulty: 5,
    enemyIds: ['void_loop_phantom_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 300, gold: 600, memoryShards: 33 }
  },
  {
    id: 'ch6_stage_036',
    name: '古老虚空',
    chapter: 6,
    stageNumber: 36,
    description: '这里封印着最古老的虚空，连现实都无法触及。',
    background: 'ancient_void',
    difficulty: 5,
    enemyIds: ['ancient_void_being_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 305, gold: 610, memoryShards: 33 }
  },
  {
    id: 'ch6_stage_037',
    name: '虚空意志',
    chapter: 6,
    stageNumber: 37,
    description: '虚空凝聚出了自己的意志，它要驱逐你这个入侵者。',
    background: 'will_of_void',
    difficulty: 5,
    enemyIds: ['void_will_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 310, gold: 620, memoryShards: 34 }
  },
  {
    id: 'ch6_stage_038',
    name: '虚空漩涡',
    chapter: 6,
    stageNumber: 38,
    description: '一个巨大的虚空漩涡正在形成，吞噬着周围的一切存在。',
    background: 'void_vortex',
    difficulty: 5,
    enemyIds: ['vortex_guardian_void_001', 'sucked_void_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 315, gold: 630, memoryShards: 34 }
  },
  {
    id: 'ch6_stage_039',
    name: '最后的深入',
    chapter: 6,
    stageNumber: 39,
    description: '进入精英区域前的最后深入，你将面对虚空最深的秘密。',
    background: 'final_void_chamber',
    difficulty: 5,
    enemyIds: ['void_sentinel_001', 'deep_void_guardian_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 320, gold: 640, memoryShards: 35 }
  },
  {
    id: 'ch6_stage_040',
    name: '高级虚空兽',
    chapter: 6,
    stageNumber: 40,
    description: '一只巨大的虚空古龙从虚空深处升起，它是这片边境的真正霸主。',
    background: 'high_void_beast_arena',
    difficulty: 5,
    enemyIds: ['void_dragon_001'],
    enemyLevel: 6,
    isBossLevel: true,
    rewards: { exp: 500, gold: 1220, memoryShards: 106 }
  },
  // ========== 精英区域 (第41-49关) 难度5 ==========
  {
    id: 'ch6_stage_041',
    name: '虚空核心',
    chapter: 6,
    stageNumber: 41,
    description: '精英区域的起始，虚空的最深处，黑暗与虚无达到极致。',
    background: 'void_core',
    difficulty: 5,
    enemyIds: ['core_void_defender_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 360, gold: 720, memoryShards: 36 }
  },
  {
    id: 'ch6_stage_042',
    name: '虚空王座',
    chapter: 6,
    stageNumber: 42,
    description: '一座由虚空能量构成的王座，散发着毁灭性的虚无之力。',
    background: 'void_throne',
    difficulty: 5,
    enemyIds: ['throne_usurper_void_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 365, gold: 730, memoryShards: 36 }
  },
  {
    id: 'ch6_stage_043',
    name: '无尽虚空',
    chapter: 6,
    stageNumber: 43,
    description: '虚空似乎没有边界，延伸到无限的黑暗之中。',
    background: 'endless_void_zone',
    difficulty: 5,
    enemyIds: ['infinite_void_entity_001', 'void_lord_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 370, gold: 740, memoryShards: 37 }
  },
  {
    id: 'ch6_stage_044',
    name: '虚空之源',
    chapter: 6,
    stageNumber: 44,
    description: '所有虚空的源头，一个古老而强大的存在守护着这里。',
    background: 'source_of_void',
    difficulty: 5,
    enemyIds: ['void_source_guardian_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 375, gold: 750, memoryShards: 37 }
  },
  {
    id: 'ch6_stage_045',
    name: '虚空典狱长',
    chapter: 6,
    stageNumber: 45,
    description: '这片虚空边境的典狱长，掌控着虚无与空间的规则。',
    background: 'void_warden_chamber',
    difficulty: 5,
    enemyIds: ['void_warden_boss_001'],
    enemyLevel: 6,
    isBossLevel: false,
    rewards: { exp: 380, gold: 760, memoryShards: 38 }
  },
  {
    id: 'ch6_stage_046',
    name: '禁忌虚空',
    chapter: 6,
    stageNumber: 46,
    description: '禁忌的虚空被封印在此，任何进入者都将面对最可怕的噩梦。',
    background: 'forbidden_void',
    difficulty: 5,
    enemyIds: ['forbidden_void_keeper_001', 'cursed_void_beast_001'],
    enemyLevel: 7,
    isBossLevel: false,
    rewards: { exp: 385, gold: 770, memoryShards: 38 }
  },
  {
    id: 'ch6_stage_047',
    name: '虚空的真相',
    chapter: 6,
    stageNumber: 47,
    description: '开始接近虚空边境的真相，守卫变得更加疯狂而强大。',
    background: 'truth_of_void_chamber',
    difficulty: 5,
    enemyIds: ['void_truth_guardian_001'],
    enemyLevel: 7,
    isBossLevel: false,
    rewards: { exp: 390, gold: 780, memoryShards: 39 }
  },
  {
    id: 'ch6_stage_048',
    name: '虚空巅峰',
    chapter: 6,
    stageNumber: 48,
    description: '普通虚空的巅峰，在这里你将面对最强大的虚空生物。',
    background: 'peak_of_void',
    difficulty: 5,
    enemyIds: ['peak_void_being_001'],
    enemyLevel: 7,
    isBossLevel: false,
    rewards: { exp: 395, gold: 790, memoryShards: 39 }
  },
  {
    id: 'ch6_stage_049',
    name: '终极虚空守卫',
    chapter: 6,
    stageNumber: 49,
    description: '精英区域的最终守卫，击败它才能面对章节Boss。',
    background: 'ultimate_void_gate',
    difficulty: 5,
    enemyIds: ['ultimate_void_sentinel_001', 'ultimate_void_defender_001'],
    enemyLevel: 7,
    isBossLevel: false,
    rewards: { exp: 400, gold: 800, memoryShards: 40 }
  },
  // ========== 章节Boss (第50关) 难度6 ==========
  {
    id: 'ch6_stage_050',
    name: '虚空之主',
    chapter: 6,
    stageNumber: 50,
    description: '虚空边境的真正主宰，它是虚无的化身，掌控着所有被吞噬的世界与存在。它能创造空间裂缝，将一切拉入永恒的虚无。只有战胜它，才能从虚空中生还。',
    background: 'lord_of_void_throne',
    difficulty: 6,
    enemyIds: ['void_overlord_001'],
    enemyLevel: 8,
    isBossLevel: true,
    rewards: { exp: 850, gold: 2200, memoryShards: 200 }
  }
];

export default Chapter6Stages;
